export enum Permission {
  // Case Permissions
  CASE_CREATE = 'CASE_CREATE',
  CASE_READ = 'CASE_READ',
  CASE_UPDATE = 'CASE_UPDATE',
  CASE_DELETE = 'CASE_DELETE',

  // Document Permissions
  DOCUMENT_CREATE = 'DOCUMENT_CREATE',
  DOCUMENT_READ = 'DOCUMENT_READ',
  DOCUMENT_UPDATE = 'DOCUMENT_UPDATE',
  DOCUMENT_DELETE = 'DOCUMENT_DELETE',

  // Billing Permissions
  BILLING_CREATE = 'BILLING_CREATE',
  BILLING_READ = 'BILLING_READ',
  BILLING_UPDATE = 'BILLING_UPDATE',
  BILLING_DELETE = 'BILLING_DELETE',

  // User Management
  USER_MANAGE = 'USER_MANAGE',

  // System Administration
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
}
