export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SENIOR_PARTNER = 'SENIOR_PARTNER',
  PARTNER = 'PARTNER',
  ASSOCIATE = 'ASSOCIATE',
  PARALEGAL = 'PARALEGAL',
  LEGAL_SECRETARY = 'LEGAL_SECRETARY',
  ADMINISTRATOR = 'ADMINISTRATOR',
  CLIENT_USER = 'CLIENT_USER',
  GUEST = 'GUEST',
}
