import { IsString, IsOptional, IsEnum, IsDateString, IsArray, IsObject } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export enum ReportType {
  CASE_SUMMARY = 'case_summary',
  BILLING = 'billing',
  TIME_ENTRY = 'time_entry',
  DISCOVERY = 'discovery',
  JUDGE_STATS = 'judge_stats',
  PRACTICE_AREA = 'practice_area',
  ATTORNEY_PRODUCTIVITY = 'attorney_productivity',
  CLIENT_MATTER = 'client_matter',
  FINANCIAL = 'financial',
  CUSTOM = 'custom',
}

export enum ReportFormat {
  PDF = 'pdf',
  EXCEL = 'excel',
  CSV = 'csv',
  JSON = 'json',
}

export enum ReportStatus {
  PENDING = 'pending',
  GENERATING = 'generating',
  COMPLETED = 'completed',
  FAILED = 'failed',
}

export class GenerateReportDto {
  @ApiProperty({
    description: 'Report type',
    enum: ReportType,
  })
  @IsEnum(ReportType)
  type!: ReportType;

  @ApiProperty({
    description: 'Report title',
    example: 'Monthly Billing Report - December 2024',
  })
  @IsString()
  title!: string;

  @ApiPropertyOptional({
    description: 'Report description',
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({
    description: 'Start date for report data',
    example: '2024-01-01',
  })
  @IsOptional()
  @IsDateString()
  startDate?: string;

  @ApiPropertyOptional({
    description: 'End date for report data',
    example: '2024-12-31',
  })
  @IsOptional()
  @IsDateString()
  endDate?: string;

  @ApiProperty({
    description: 'Report output format',
    enum: ReportFormat,
    default: ReportFormat.PDF,
  })
  @IsEnum(ReportFormat)
  format: ReportFormat = ReportFormat.PDF;

  @ApiPropertyOptional({
    description: 'Report filters',
    example: { caseId: 'case-123', attorneyId: 'attorney-456' },
  })
  @IsOptional()
  @IsObject()
  filters?: Record<string, unknown>;

  @ApiPropertyOptional({
    description: 'Report parameters/options',
    example: { includeCharts: true, groupBy: 'attorney' },
  })
  @IsOptional()
  @IsObject()
  parameters?: Record<string, unknown>;

  @ApiPropertyOptional({
    description: 'Email recipients for report delivery',
  })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  emailRecipients?: string[];
}

export class ReportDto {
  @ApiProperty({ description: 'Report ID' })
  id!: string;

  @ApiProperty({ description: 'Report type', enum: ReportType })
  type!: ReportType;

  @ApiProperty({ description: 'Report title' })
  title!: string;

  @ApiProperty({ description: 'Report description' })
  description?: string;

  @ApiProperty({ description: 'Report status', enum: ReportStatus })
  status!: ReportStatus;

  @ApiProperty({ description: 'Report format', enum: ReportFormat })
  format!: ReportFormat;

  @ApiProperty({ description: 'Generated by user ID' })
  generatedBy!: string;

  @ApiProperty({ description: 'Generated by user name' })
  generatedByName!: string;

  @ApiProperty({ description: 'Start date' })
  startDate?: Date;

  @ApiProperty({ description: 'End date' })
  endDate?: Date;

  @ApiProperty({ description: 'Filters applied' })
  filters?: Record<string, unknown>;

  @ApiProperty({ description: 'Report parameters' })
  parameters?: Record<string, unknown>;

  @ApiProperty({ description: 'File size in bytes' })
  fileSize?: number;

  @ApiProperty({ description: 'File URL for download' })
  fileUrl?: string;

  @ApiProperty({ description: 'Error message if failed' })
  errorMessage?: string;

  @ApiProperty({ description: 'Created at' })
  createdAt!: Date;

  @ApiProperty({ description: 'Completed at' })
  completedAt?: Date;

  @ApiProperty({ description: 'Expires at' })
  expiresAt?: Date;
}

export class ReportListDto {
  @ApiProperty({ description: 'Reports list', type: [ReportDto] })
  reports!: ReportDto[];

  @ApiProperty({ description: 'Total count' })
  total!: number;

  @ApiProperty({ description: 'Page number' })
  page!: number;

  @ApiProperty({ description: 'Items per page' })
  limit!: number;
}

export class ReportTemplateDto {
  @ApiProperty({ description: 'Template ID' })
  id!: string;

  @ApiProperty({ description: 'Template name' })
  name!: string;

  @ApiProperty({ description: 'Template description' })
  description!: string;

  @ApiProperty({ description: 'Report type', enum: ReportType })
  type!: ReportType;

  @ApiProperty({ description: 'Default format', enum: ReportFormat })
  defaultFormat!: ReportFormat;

  @ApiProperty({ description: 'Available filters' })
  availableFilters!: FilterDefinition[];

  @ApiProperty({ description: 'Available parameters' })
  availableParameters!: ParameterDefinition[];

  @ApiProperty({ description: 'Is system template' })
  isSystem!: boolean;

  @ApiProperty({ description: 'Created by user ID' })
  createdBy?: string;
}

export class FilterDefinition {
  @ApiProperty({ description: 'Filter name' })
  name!: string;

  @ApiProperty({ description: 'Filter label' })
  label!: string;

  @ApiProperty({ description: 'Filter type' })
  type!: 'text' | 'date' | 'select' | 'multiselect' | 'number';

  @ApiProperty({ description: 'Filter options (for select types)' })
  options?: { value: string; label: string }[];

  @ApiProperty({ description: 'Is required' })
  required!: boolean;

  @ApiProperty({ description: 'Default value' })
  defaultValue?: unknown;
}

export class ParameterDefinition {
  @ApiProperty({ description: 'Parameter name' })
  name!: string;

  @ApiProperty({ description: 'Parameter label' })
  label!: string;

  @ApiProperty({ description: 'Parameter type' })
  type!: 'boolean' | 'text' | 'number' | 'select';

  @ApiProperty({ description: 'Parameter options (for select type)' })
  options?: { value: string; label: string }[];

  @ApiProperty({ description: 'Default value' })
  defaultValue?: unknown;

  @ApiProperty({ description: 'Description' })
  description?: string;
}

export class CaseSummaryReportData {
  @ApiProperty({ description: 'Case information' })
  caseInfo!: {
    caseNumber: string;
    title: string;
    status: string;
    practiceArea: string;
    openDate: Date;
    closeDate?: Date;
  };

  @ApiProperty({ description: 'Client information' })
  clientInfo!: {
    name: string;
    contactPerson: string;
    email: string;
  };

  @ApiProperty({ description: 'Case team members' })
  teamMembers!: {
    name: string;
    role: string;
    hours: number;
    amount: number;
  }[];

  @ApiProperty({ description: 'Financial summary' })
  financialSummary!: {
    totalBilled: number;
    totalCollected: number;
    wipValue: number;
    arValue: number;
  };

  @ApiProperty({ description: 'Key events timeline' })
  timeline!: {
    date: Date;
    event: string;
    description: string;
  }[];

  @ApiProperty({ description: 'Document statistics' })
  documentStats!: {
    totalDocuments: number;
    byType: { [type: string]: number };
  };
}

export class BillingReportData {
  @ApiProperty({ description: 'Period information' })
  period!: {
    startDate: Date;
    endDate: Date;
    label: string;
  };

  @ApiProperty({ description: 'Summary metrics' })
  summary!: {
    totalBilled: number;
    totalCollected: number;
    totalHours: number;
    avgBillingRate: number;
    realizationRate: number;
  };

  @ApiProperty({ description: 'Billing by attorney' })
  byAttorney!: {
    name: string;
    hours: number;
    amount: number;
    rate: number;
  }[];

  @ApiProperty({ description: 'Billing by practice area' })
  byPracticeArea!: {
    practiceArea: string;
    hours: number;
    amount: number;
  }[];

  @ApiProperty({ description: 'Billing by client' })
  byClient!: {
    clientName: string;
    hours: number;
    amount: number;
  }[];

  @ApiProperty({ description: 'Time entries detail' })
  timeEntries?: {
    date: Date;
    attorney: string;
    caseNumber: string;
    description: string;
    hours: number;
    rate: number;
    amount: number;
  }[];
}

export class DownloadReportDto {
  @ApiProperty({ description: 'Download URL' })
  downloadUrl!: string;

  @ApiProperty({ description: 'File name' })
  fileName!: string;

  @ApiProperty({ description: 'File size in bytes' })
  fileSize!: number;

  @ApiProperty({ description: 'Content type' })
  contentType!: string;

  @ApiProperty({ description: 'URL expires at' })
  expiresAt!: Date;
}
