import React from "react";
import { PATHS } from "../paths.config";
import * as Components from "./lazyComponents";

export const COMPONENT_MAP: Record<
  string,
  React.LazyExoticComponent<React.ComponentType<unknown>>
> = {
  [PATHS.DASHBOARD]: Components.Dashboard,
  [PATHS.CREATE_CASE]: Components.NewCasePage,
  [PATHS.CASES]: Components.CaseModule,
  [PATHS.CASES_OVERVIEW]: Components.CaseOverviewDashboard,
  [PATHS.CASES_CALENDAR]: Components.CaseCalendar,
  [PATHS.CASES_ANALYTICS]: Components.CaseAnalyticsDashboard,
  [PATHS.CASES_INTAKE]: Components.NewCaseIntakeForm,
  [PATHS.CASES_OPERATIONS]: Components.CaseOperationsCenter,
  [PATHS.CASES_INSIGHTS]: Components.CaseInsightsDashboard,
  [PATHS.CASES_FINANCIALS]: Components.CaseFinancialsCenter,
  [PATHS.DOCKET]: Components.DocketManager,
  [PATHS.CORRESPONDENCE]: Components.CorrespondenceManager,
  [PATHS.WORKFLOWS]: Components.MasterWorkflow,
  [PATHS.DOCUMENTS]: Components.DocumentManager,
  [PATHS.DRAFTING]: Components.DraftingDashboard,
  [PATHS.WAR_ROOM]: Components.WarRoom,
  [PATHS.EXHIBITS]: Components.ExhibitManager,
  [PATHS.DISCOVERY]: Components.DiscoveryPlatform,
  [PATHS.EVIDENCE]: Components.EvidenceVault,
  [PATHS.RESEARCH]: Components.ResearchTool,
  [PATHS.PRACTICE]: Components.FirmOperations,
  [PATHS.BILLING]: Components.BillingDashboard,
  [PATHS.CRM]: Components.ClientCRM,
  [PATHS.COMPLIANCE]: Components.ComplianceDashboard,
  [PATHS.ADMIN]: Components.AdminPanel,
  "/admin/theme-settings": Components.ThemeSettings,
  [PATHS.MESSAGES]: Components.SecureMessenger,
  [PATHS.ENTITIES]: Components.EntityDirector,
  [PATHS.DATA_PLATFORM]: Components.AdminDatabaseControl,
  [PATHS.ANALYTICS]: Components.AnalyticsDashboard,
  [PATHS.JURISDICTION]: Components.JurisdictionManager,
  [PATHS.CALENDAR]: Components.CalendarView,
  [PATHS.RULES_ENGINE]: Components.RulesPlatform,
  [PATHS.PROFILE]: Components.UserProfileManager,
  [PATHS.DAF]: Components.DafDashboard,
  [PATHS.PLEADING_BUILDER]: Components.PleadingBuilder,
  [PATHS.LIBRARY]: Components.KnowledgeBase,
  [PATHS.LITIGATION_BUILDER]: Components.LitigationBuilder,
  [PATHS.CLAUSES]: Components.ClauseLibrary,
  [PATHS.CITATIONS]: Components.CitationManager,
  [PATHS.THEME]: Components.ThemeCustomizer,
};
