#!/bin/bash
# ESLint Quick Commands - LexiFlow Frontend

echo "🔍 ESLint Quick Reference"
echo "=========================="
echo ""
echo "Basic Commands:"
echo "  npm run lint          - Run linting (allows 100 warnings)"
echo "  npm run lint:fix      - Auto-fix issues"
echo "  npm run lint:strict   - Strict mode (0 warnings)"
echo "  npm run type-check    - TypeScript type checking"
echo "  npm run validate      - Run type-check + lint"
echo ""
echo "Advanced Options:"
echo "  npm run lint -- --cache              - Use cache for faster runs"
echo "  npm run lint -- --fix-dry-run       - Preview auto-fixes"
echo "  npm run lint -- --format json       - JSON output"
echo "  npm run lint -- path/to/file.tsx    - Lint specific file"
echo ""
echo "Useful Flags:"
echo "  --debug               - Show debug info"
echo "  --quiet               - Report errors only"
echo "  --max-warnings 0      - Treat warnings as errors"
echo ""
echo "Examples:"
echo "  npx eslint App.tsx --fix"
echo "  npm run lint -- --quiet"
echo "  npm run lint -- components/"
echo ""
