module.exports = {
  testEnvironment: 'node',
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  moduleFileExtensions: ['js', 'json', 'ts'],
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: {
          module: 'commonjs',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          target: 'ES2021',
          types: ['jest', 'node'],
        },
        isolatedModules: true,
        diagnostics: {
          warnOnly: true,
        },
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.interface.ts',
    '!**/*.module.ts',
    '!**/*.entity.ts',
    '!**/*.dto.ts',
    '!**/*.enum.ts',
    '!**/main.ts',
    '!**/migrations/**',
    '!**/seeds/**',
    '!**/scripts/**',
    '!**/config/**',
  ],
  coverageDirectory: '../coverage',
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
    '^@/(.*)$': '<rootDir>/$1',
    '^@shared/(.*)$': '<rootDir>/shared/$1',
    '^@shared$': '<rootDir>/shared',
    '^@core/(.*)$': '<rootDir>/$1',
    '^@core$': '<rootDir>',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@auth$': '<rootDir>/auth',
    '^@security/(.*)$': '<rootDir>/security/$1',
    '^@security$': '<rootDir>/security',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@common$': '<rootDir>/common',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@config$': '<rootDir>/config',
    '^@database/(.*)$': '<rootDir>/database/$1',
    '^@database$': '<rootDir>/database',
    '^@errors/(.*)$': '<rootDir>/errors/$1',
    '^@errors$': '<rootDir>/errors',
    '^@monitoring/(.*)$': '<rootDir>/monitoring/$1',
    '^@monitoring$': '<rootDir>/monitoring',
    '^@performance/(.*)$': '<rootDir>/performance/$1',
    '^@performance$': '<rootDir>/performance',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@users$': '<rootDir>/users',
    '^@cases/(.*)$': '<rootDir>/cases/$1',
    '^@cases$': '<rootDir>/cases',
    '^@documents/(.*)$': '<rootDir>/documents/$1',
    '^@documents$': '<rootDir>/documents',
    '^@discovery/(.*)$': '<rootDir>/discovery/$1',
    '^@discovery$': '<rootDir>/discovery',
    '^@evidence/(.*)$': '<rootDir>/evidence/$1',
    '^@evidence$': '<rootDir>/evidence',
    '^@billing/(.*)$': '<rootDir>/billing/$1',
    '^@billing$': '<rootDir>/billing',
    '^@analytics/(.*)$': '<rootDir>/analytics/$1',
    '^@analytics$': '<rootDir>/analytics',
    '^@communications/(.*)$': '<rootDir>/communications/$1',
    '^@communications$': '<rootDir>/communications',
    '^@integrations/(.*)$': '<rootDir>/integrations/$1',
    '^@integrations$': '<rootDir>/integrations',
    '^@graphql/(.*)$': '<rootDir>/graphql/$1',
    '^@graphql$': '<rootDir>/graphql',
    '^@realtime/(.*)$': '<rootDir>/realtime/$1',
    '^@realtime$': '<rootDir>/realtime',
    '^@types/(.*)$': '<rootDir>/types/$1',
    '^@types$': '<rootDir>/types',
    '^@sharedTypes/(.*)$': '<rootDir>/shared-types/$1',
    '^@sharedTypes$': '<rootDir>/shared-types',
    '^@case-teams/(.*)$': '<rootDir>/case-teams/$1',
    '^@case-teams$': '<rootDir>/case-teams',
    '^@tasks/(.*)$': '<rootDir>/tasks/$1',
    '^@tasks$': '<rootDir>/tasks',
    '^@organizations/(.*)$': '<rootDir>/organizations/$1',
    '^@organizations$': '<rootDir>/organizations',
  },
  modulePathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/coverage/',
    '<rootDir>/node_modules/',
    '<rootDir>/../archived/',
  ],
  setupFilesAfterEnv: ['<rootDir>/../test/setup/testSetup.ts'],
  testTimeout: 30000,
  maxWorkers: '50%',
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
