module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  moduleFileExtensions: ['js', 'json', 'ts'],
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: {
          module: 'commonjs',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          target: 'ES2021',
          types: ['jest', 'node'],
        },
        isolatedModules: true,
        diagnostics: {
          warnOnly: true,
        },
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*\\.mjs$)'],
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.interface.ts',
    '!**/*.module.ts',
    '!**/*.entity.ts',
    '!**/*.dto.ts',
    '!**/*.enum.ts',
    '!**/main.ts',
    '!**/migrations/**',
    '!**/seeds/**',
    '!**/scripts/**',
    '!**/config/**',
  ],
  coverageDirectory: '../coverage',
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/$1',
    '^@/(.*)$': '<rootDir>/$1',
    '^@shared/(.*)$': '<rootDir>/shared/$1',
    '^@shared$': '<rootDir>/shared',
    '^@core/(.*)$': '<rootDir>/$1',
    '^@core$': '<rootDir>',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@auth$': '<rootDir>/auth',
    '^@security/(.*)$': '<rootDir>/security/$1',
    '^@security$': '<rootDir>/security',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@common$': '<rootDir>/common',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@config$': '<rootDir>/config',
    '^@database/(.*)$': '<rootDir>/database/$1',
    '^@database$': '<rootDir>/database',
    '^@errors/(.*)$': '<rootDir>/errors/$1',
    '^@errors$': '<rootDir>/errors',
    '^@monitoring/(.*)$': '<rootDir>/monitoring/$1',
    '^@monitoring$': '<rootDir>/monitoring',
    '^@performance/(.*)$': '<rootDir>/performance/$1',
    '^@performance$': '<rootDir>/performance',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@users$': '<rootDir>/users',
    '^@cases/(.*)$': '<rootDir>/cases/$1',
    '^@cases$': '<rootDir>/cases',
    '^@documents/(.*)$': '<rootDir>/documents/$1',
    '^@documents$': '<rootDir>/documents',
    '^@discovery/(.*)$': '<rootDir>/discovery/$1',
    '^@discovery$': '<rootDir>/discovery',
    '^@evidence/(.*)$': '<rootDir>/evidence/$1',
    '^@evidence$': '<rootDir>/evidence',
    '^@billing/(.*)$': '<rootDir>/billing/$1',
    '^@billing$': '<rootDir>/billing',
    '^@analytics/(.*)$': '<rootDir>/analytics/$1',
    '^@analytics$': '<rootDir>/analytics',
    '^@communications/(.*)$': '<rootDir>/communications/$1',
    '^@communications$': '<rootDir>/communications',
    '^@integrations/(.*)$': '<rootDir>/integrations/$1',
    '^@integrations$': '<rootDir>/integrations',
    '^@graphql/(.*)$': '<rootDir>/graphql/$1',
    '^@graphql$': '<rootDir>/graphql',
    '^@realtime/(.*)$': '<rootDir>/realtime/$1',
    '^@realtime$': '<rootDir>/realtime',
    '^@types/(.*)$': '<rootDir>/types/$1',
    '^@types$': '<rootDir>/types',
    '^@sharedTypes/(.*)$': '<rootDir>/shared-types/$1',
    '^@sharedTypes$': '<rootDir>/shared-types',
    '^@case-teams/(.*)$': '<rootDir>/case-teams/$1',
    '^@case-teams$': '<rootDir>/case-teams',
    '^@tasks/(.*)$': '<rootDir>/tasks/$1',
    '^@tasks$': '<rootDir>/tasks',
    '^@organizations/(.*)$': '<rootDir>/organizations/$1',
    '^@organizations$': '<rootDir>/organizations',
    '^@ai-dataops/(.*)$': '<rootDir>/ai-dataops/$1',
    '^@ai-dataops$': '<rootDir>/ai-dataops',
    '^@ai-ops/(.*)$': '<rootDir>/ai-ops/$1',
    '^@ai-ops$': '<rootDir>/ai-ops',
    '^@analytics-dashboard/(.*)$': '<rootDir>/analytics-dashboard/$1',
    '^@analytics-dashboard$': '<rootDir>/analytics-dashboard',
    '^@api-keys/(.*)$': '<rootDir>/api-keys/$1',
    '^@api-keys$': '<rootDir>/api-keys',
    '^@api-security/(.*)$': '<rootDir>/api-security/$1',
    '^@api-security$': '<rootDir>/api-security',
    '^@audit/(.*)$': '<rootDir>/audit/$1',
    '^@audit$': '<rootDir>/audit',
    '^@authorization/(.*)$': '<rootDir>/authorization/$1',
    '^@authorization$': '<rootDir>/authorization',
    '^@backup-restore/(.*)$': '<rootDir>/backup-restore/$1',
    '^@backup-restore$': '<rootDir>/backup-restore',
    '^@backups/(.*)$': '<rootDir>/backups/$1',
    '^@backups$': '<rootDir>/backups',
    '^@bluebook/(.*)$': '<rootDir>/bluebook/$1',
    '^@bluebook$': '<rootDir>/bluebook',
    '^@calendar/(.*)$': '<rootDir>/calendar/$1',
    '^@calendar$': '<rootDir>/calendar',
    '^@case-phases/(.*)$': '<rootDir>/case-phases/$1',
    '^@case-phases$': '<rootDir>/case-phases',
    '^@citations/(.*)$': '<rootDir>/citations/$1',
    '^@citations$': '<rootDir>/citations',
    '^@clauses/(.*)$': '<rootDir>/clauses/$1',
    '^@clauses$': '<rootDir>/clauses',
    '^@clients/(.*)$': '<rootDir>/clients/$1',
    '^@clients$': '<rootDir>/clients',
    '^@compliance/(.*)$': '<rootDir>/compliance/$1',
    '^@compliance$': '<rootDir>/compliance',
    '^@docket/(.*)$': '<rootDir>/docket/$1',
    '^@docket$': '<rootDir>/docket',
    '^@document-versions/(.*)$': '<rootDir>/document-versions/$1',
    '^@document-versions$': '<rootDir>/document-versions',
    '^@drafting/(.*)$': '<rootDir>/drafting/$1',
    '^@drafting$': '<rootDir>/drafting',
    '^@etl-pipelines/(.*)$': '<rootDir>/etl-pipelines/$1',
    '^@etl-pipelines$': '<rootDir>/etl-pipelines',
    '^@exhibits/(.*)$': '<rootDir>/exhibits/$1',
    '^@exhibits$': '<rootDir>/exhibits',
    '^@file-storage/(.*)$': '<rootDir>/file-storage/$1',
    '^@file-storage$': '<rootDir>/file-storage',
    '^@health/(.*)$': '<rootDir>/health/$1',
    '^@health$': '<rootDir>/health',
    '^@hr/(.*)$': '<rootDir>/hr/$1',
    '^@hr$': '<rootDir>/hr',
    '^@judges/(.*)$': '<rootDir>/judges/$1',
    '^@judges$': '<rootDir>/judges',
    '^@jurisdictions/(.*)$': '<rootDir>/jurisdictions/$1',
    '^@jurisdictions$': '<rootDir>/jurisdictions',
    '^@knowledge/(.*)$': '<rootDir>/knowledge/$1',
    '^@knowledge$': '<rootDir>/knowledge',
    '^@legal-entities/(.*)$': '<rootDir>/legal-entities/$1',
    '^@legal-entities$': '<rootDir>/legal-entities',
    '^@matters/(.*)$': '<rootDir>/matters/$1',
    '^@matters$': '<rootDir>/matters',
    '^@messenger/(.*)$': '<rootDir>/messenger/$1',
    '^@messenger$': '<rootDir>/messenger',
    '^@metrics/(.*)$': '<rootDir>/metrics/$1',
    '^@metrics$': '<rootDir>/metrics',
    '^@migrations/(.*)$': '<rootDir>/migrations/$1',
    '^@migrations$': '<rootDir>/migrations',
    '^@motions/(.*)$': '<rootDir>/motions/$1',
    '^@motions$': '<rootDir>/motions',
    '^@notifications/(.*)$': '<rootDir>/notifications/$1',
    '^@notifications$': '<rootDir>/notifications',
    '^@ocr/(.*)$': '<rootDir>/ocr/$1',
    '^@ocr$': '<rootDir>/ocr',
    '^@parties/(.*)$': '<rootDir>/parties/$1',
    '^@parties$': '<rootDir>/parties',
    '^@pipelines/(.*)$': '<rootDir>/pipelines/$1',
    '^@pipelines$': '<rootDir>/pipelines',
    '^@pleadings/(.*)$': '<rootDir>/pleadings/$1',
    '^@pleadings$': '<rootDir>/pleadings',
    '^@processing-jobs/(.*)$': '<rootDir>/processing-jobs/$1',
    '^@processing-jobs$': '<rootDir>/processing-jobs',
    '^@production/(.*)$': '<rootDir>/production/$1',
    '^@production$': '<rootDir>/production',
    '^@projects/(.*)$': '<rootDir>/projects/$1',
    '^@projects$': '<rootDir>/projects',
    '^@query-workbench/(.*)$': '<rootDir>/query-workbench/$1',
    '^@query-workbench$': '<rootDir>/query-workbench',
    '^@queues/(.*)$': '<rootDir>/queues/$1',
    '^@queues$': '<rootDir>/queues',
    '^@reports/(.*)$': '<rootDir>/reports/$1',
    '^@reports$': '<rootDir>/reports',
    '^@risks/(.*)$': '<rootDir>/risks/$1',
    '^@risks$': '<rootDir>/risks',
    '^@schema-management/(.*)$': '<rootDir>/schema-management/$1',
    '^@schema-management$': '<rootDir>/schema-management',
    '^@scripts/(.*)$': '<rootDir>/scripts/$1',
    '^@scripts$': '<rootDir>/scripts',
    '^@search/(.*)$': '<rootDir>/search/$1',
    '^@search$': '<rootDir>/search',
    '^@sync/(.*)$': '<rootDir>/sync/$1',
    '^@sync$': '<rootDir>/sync',
    '^@telemetry/(.*)$': '<rootDir>/telemetry/$1',
    '^@telemetry$': '<rootDir>/telemetry',
    '^@test-utils/(.*)$': '<rootDir>/test-utils/$1',
    '^@test-utils$': '<rootDir>/test-utils',
    '^@trial/(.*)$': '<rootDir>/trial/$1',
    '^@trial$': '<rootDir>/trial',
    '^@versioning/(.*)$': '<rootDir>/versioning/$1',
    '^@versioning$': '<rootDir>/versioning',
    '^@war-room/(.*)$': '<rootDir>/war-room/$1',
    '^@war-room$': '<rootDir>/war-room',
    '^@webhooks/(.*)$': '<rootDir>/webhooks/$1',
    '^@webhooks$': '<rootDir>/webhooks',
    '^@workflow/(.*)$': '<rootDir>/workflow/$1',
    '^@workflow$': '<rootDir>/workflow',
  },
  modulePathIgnorePatterns: [
    '<rootDir>/dist/',
    '<rootDir>/coverage/',
    '<rootDir>/node_modules/',
    '<rootDir>/../archived/',
  ],
  setupFilesAfterEnv: ['<rootDir>/../test/setup/testSetup.ts'],
  testTimeout: 30000,
  maxWorkers: '50%',
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
