/**
 * Migration helper file
 * Re-exports types from @lexiflow/shared-types for gradual migration
 *
 * This file allows the frontend to start using shared types without breaking existing imports.
 * Over time, direct imports should be updated to use @lexiflow/shared-types instead.
 */

// Re-export shared entities
export {
  BaseEntity,
  BaseEntityWithVersion,
  UUID,
  CaseId,
  UserId,
  OrgId,
  GroupId,
  DocumentId,
  EvidenceId,
  TaskId,
  EntityId,
  PartyId,
  MotionId,
  DocketId,
  ProjectId,
  WorkflowTemplateId,
  InvoiceId,
  ClientId,
  type Case,
  type CaseSummary,
  type CaseStats,
  type Document,
  type DocumentSummary,
  type DocumentVersion,
  type User,
  type UserProfile,
  type UserSummary,
} from '@lexiflow/shared-types';

// Re-export shared enums
export {
  CaseStatus,
  CaseType,
  MatterType,
  BillingModel,
  DocumentStatus,
  DocumentType,
  DocumentAccessLevel,
  OcrStatus,
  UserRole,
  UserStatus,
  DiscoveryType,
  DiscoveryStatus,
  DiscoveryRequestStatus,
  ESICollectionStatus,
  LegalHoldStatus,
  PrivilegeBasis,
  ConferralResult,
  ConferralMethod,
  InvoiceStatus,
  PaymentStatus,
  WIPStatus,
  ExpenseStatus,
  TrustAccountStatus,
  CurrencyCode,
  LedesActivityCode,
  LedesTaskCode,
  MotionType,
  MotionStatus,
  MotionOutcome,
  DocketEntryType,
  ExhibitStatus,
  ExhibitParty,
  ServiceStatus,
  ServiceMethod,
  EvidenceType,
  AdmissibilityStatus,
  CustodyActionType,
  CommunicationType,
  CommunicationDirection,
  CommunicationStatus,
  TaskStatus,
  StageStatus,
  TaskDependencyType,
  OrganizationType,
  EntityType,
  EntityRole,
  RiskCategory,
  RiskLevel,
  RiskStatus,
  LegalRuleType,
  NavCategory,
} from '@lexiflow/shared-types';

// Re-export shared DTOs
export {
  type PaginatedResponse,
  type PaginationParams,
  type FilterParams,
  type QueryParams,
  type ApiResponse,
  type ApiError,
  type ResponseMeta,
  type SuccessResponse,
  type ErrorResponse,
  type BatchOperationResult,
  type BatchOperationError,
} from '@lexiflow/shared-types';

// Re-export shared interfaces
export {
  type LoginCredentials,
  type LoginResponse,
  type AuthenticatedUser,
  type JwtPayload,
  type RefreshTokenRequest,
  type TwoFactorSetupResponse,
  type TwoFactorVerificationRequest,
  type PasswordResetRequest,
  type PasswordResetConfirmation,
  type ChangePasswordRequest,
  type SessionInfo,
} from '@lexiflow/shared-types';
