
export const ENTERPRISE_SCHEMA_DDL = `-- Enterprise Legal Schema (PostgreSQL 15+)
-- Generated by LexiFlow Architecture Engine

-- 1. EXTENSIONS & CONFIG
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. ENUMS
CREATE TYPE user_role AS ENUM ('Senior Partner', 'Associate', 'Paralegal', 'Administrator', 'Client User');
CREATE TYPE case_status AS ENUM ('Discovery', 'Trial', 'Settled', 'Closed', 'Appeal');
CREATE TYPE risk_level AS ENUM ('Low', 'Medium', 'High');

-- 3. AUDIT FUNCTION
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

-- 4. CORE TABLES

-- ORGANIZATIONS (Multi-tenancy Root)
CREATE TABLE organizations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50),
    domain VARCHAR(255),
    status VARCHAR(50) DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- USERS (Identity)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_id UUID REFERENCES organizations(id),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255), -- Managed by Auth Provider
    role user_role NOT NULL,
    office VARCHAR(100),
    mfa_enabled BOOLEAN DEFAULT FALSE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- CASES (Matters)
CREATE TABLE cases (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    org_id UUID REFERENCES organizations(id),
    
    -- Matter Details
    title VARCHAR(500) NOT NULL,
    matter_type VARCHAR(100),
    status case_status DEFAULT 'Discovery',
    jurisdiction VARCHAR(255),
    court VARCHAR(255),
    judge VARCHAR(255),
    filing_date DATE,
    
    -- Financials
    billing_model VARCHAR(50),
    estimated_value NUMERIC(15, 2),
    
    -- Internal
    owner_id UUID REFERENCES users(id),
    is_consolidated BOOLEAN DEFAULT FALSE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(id),
    updated_by UUID REFERENCES users(id)
);

-- PARTIES (Normalized)
CREATE TABLE parties (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) CHECK (type IN ('Individual', 'Corporation', 'Government')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- CASE_PARTIES (Junction)
CREATE TABLE case_parties (
    case_id UUID REFERENCES cases(id) ON DELETE CASCADE,
    party_id UUID REFERENCES parties(id),
    role VARCHAR(100) NOT NULL, -- Plaintiff, Defendant, etc.
    counsel_name VARCHAR(255),
    PRIMARY KEY (case_id, party_id)
);

-- DOCUMENTS (Metadata)
CREATE TABLE documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    case_id UUID REFERENCES cases(id),
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50),
    
    -- Storage Pointer (No BLOBs in main table)
    storage_key VARCHAR(500),
    file_size_bytes BIGINT,
    
    -- Security
    is_encrypted BOOLEAN DEFAULT FALSE,
    encryption_key_id VARCHAR(100),
    
    -- Workflow
    status VARCHAR(50) DEFAULT 'Draft',
    version_current INTEGER DEFAULT 1,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(id)
);

-- DOCUMENT_VERSIONS
CREATE TABLE document_versions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    document_id UUID REFERENCES documents(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(id)
);

-- DOCKET_ENTRIES
CREATE TABLE docket_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    case_id UUID REFERENCES cases(id),
    sequence_number INTEGER,
    date_filed DATE,
    type VARCHAR(50),
    title VARCHAR(1000),
    description TEXT,
    filed_by VARCHAR(255),
    is_sealed BOOLEAN DEFAULT FALSE,
    document_id UUID REFERENCES documents(id),
    ecf_number VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- TIME_ENTRIES (Billing)
CREATE TABLE time_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    case_id UUID REFERENCES cases(id),
    user_id UUID REFERENCES users(id),
    date_worked DATE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    description TEXT,
    rate_hourly NUMERIC(10, 2),
    total_amount NUMERIC(10, 2),
    status VARCHAR(50) DEFAULT 'Unbilled',
    invoice_id UUID, -- Future FK
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- EVIDENCE_CHAIN
CREATE TABLE evidence_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    case_id UUID REFERENCES cases(id),
    title VARCHAR(255) NOT NULL,
    type VARCHAR(50),
    blockchain_hash VARCHAR(256), -- SHA-256 Anchor
    custodian VARCHAR(255),
    status VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE custody_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evidence_id UUID REFERENCES evidence_items(id),
    action VARCHAR(100),
    actor VARCHAR(255),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    prev_hash VARCHAR(256), -- Internal Chain
    curr_hash VARCHAR(256)
);

-- 5. INDICES
CREATE INDEX idx_cases_org ON cases(org_id);
CREATE INDEX idx_documents_case ON documents(case_id);
CREATE INDEX idx_docket_case_date ON docket_entries(case_id, date_filed);
CREATE INDEX idx_time_entries_unbilled ON time_entries(case_id) WHERE status = 'Unbilled';
CREATE INDEX idx_parties_name ON parties USING GIN (to_tsvector('english', name));
CREATE INDEX idx_pacer_case_number ON pacer_cases(case_number_full);

-- 6. TRIGGERS
CREATE TRIGGER update_cases_modtime BEFORE UPDATE ON cases FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_docs_modtime BEFORE UPDATE ON documents FOR EACH ROW EXECUTE PROCEDURE update_timestamp();
CREATE TRIGGER update_users_modtime BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 7. RLS POLICIES (Example)
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
`;
