
import React from 'react';
import { ExternalLink, Bookmark, Share2, ThumbsUp, ThumbsDown, BookOpen } from 'lucide-react';
import { ResearchSession } from '../../types';
import { Card } from '../common/Card';
import { Badge } from '../common/Badge';
import { useTheme } from '../../context/ThemeContext';
import { cn } from '../../utils/cn';

interface ResearchResultsProps {
  session?: ResearchSession;
  onViewSource?: (url: string, title: string) => void;
}

export const ResearchResults: React.FC<ResearchResultsProps> = ({ session, onViewSource }) => {
  const { theme } = useTheme();

  if (!session) {
    return (
        <div className={cn("flex flex-col items-center justify-center h-full opacity-60", theme.text.tertiary)}>
            <BookOpen className="h-16 w-16 mb-4" />
            <p className="text-lg font-medium">Enter a legal query to begin research</p>
        </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center justify-between">
            <div>
                <h3 className={cn("text-lg font-bold leading-snug", theme.text.primary)}>{session.query}</h3>
                <p className={cn("text-xs mt-1", theme.text.secondary)}>Generated by LexiFlow AI • Grounded via Google Search</p>
            </div>
            <div className="flex gap-2">
                <button className={cn("p-2 border rounded transition-colors", theme.surface, theme.border.default, theme.text.secondary, `hover:${theme.surfaceHighlight}`)}><Bookmark className="h-4 w-4"/></button>
                <button className={cn("p-2 border rounded transition-colors", theme.surface, theme.border.default, theme.text.secondary, `hover:${theme.surfaceHighlight}`)}><Share2 className="h-4 w-4"/></button>
            </div>
        </div>

        <Card className={cn("shadow-md", theme.primary.border)}>
            <div className={cn("prose prose-sm max-w-none leading-relaxed whitespace-pre-line font-serif", theme.text.primary)}>
                {session.response}
            </div>
            <div className={cn("mt-6 flex items-center justify-end space-x-4 border-t pt-4", theme.border.light)}>
                <span className={cn("text-xs", theme.text.tertiary)}>Was this answer helpful?</span>
                <button className={cn("p-1.5 rounded transition-colors hover:bg-green-50 hover:text-green-600", theme.text.tertiary)}><ThumbsUp className="h-4 w-4" /></button>
                <button className={cn("p-1.5 rounded transition-colors hover:bg-red-50 hover:text-red-600", theme.text.tertiary)}><ThumbsDown className="h-4 w-4" /></button>
            </div>
        </Card>

        {session.sources.length > 0 && (
            <div>
                <h4 className={cn("text-xs font-bold uppercase tracking-wider mb-3 ml-1", theme.text.secondary)}>Authorities Cited</h4>
                <div className="grid grid-cols-1 gap-3">
                    {session.sources.map((source, idx) => (
                        <div 
                            key={idx} 
                            className={cn("p-4 rounded-lg border transition-colors shadow-sm flex flex-col group cursor-pointer", theme.surface, theme.border.default, `hover:${theme.primary.border}`)}
                            onClick={() => onViewSource && source.url && onViewSource(source.url, source.title)}
                        >
                            <div className="flex justify-between items-start">
                                <div className={cn("text-sm font-bold hover:underline line-clamp-1 flex items-center", theme.primary.text)}>
                                    {source.title} <ExternalLink className="h-3 w-3 ml-2 opacity-50"/>
                                </div>
                                <Badge variant="neutral">Web Source</Badge>
                            </div>
                            <p className={cn("text-xs mt-1 line-clamp-1 font-mono", theme.text.tertiary)}>{source.url}</p>
                            <p className={cn("text-xs mt-2 line-clamp-2", theme.text.secondary)}>{source.snippet}</p>
                        </div>
                    ))}
                </div>
            </div>
        )}
    </div>
  );
};
