/**
 * API Type Definitions for Frontend-Backend Integration
 * Generated by Agent 11 - Coordinator
 * Last Updated: 2025-12-12
 */

// ============================================================================
// AUTHENTICATION API TYPES
// ============================================================================

export interface LoginRequest {
  email: string;
  password: string;
  rememberMe?: boolean;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  user: UserProfile;
  expiresIn: number;
}

export interface RegisterRequest {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  phoneNumber?: string;
  organizationId?: string;
}

export interface RegisterResponse {
  user: UserProfile;
  message: string;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken?: string;
  expiresIn: number;
}

export interface TwoFactorSetupResponse {
  qrCodeUrl: string;
  secret: string;
  backupCodes: string[];
}

export interface TwoFactorVerifyRequest {
  code: string;
  token: string;
}

export interface OAuthCallbackRequest {
  code: string;
  state: string;
  provider: 'google' | 'microsoft';
}

// ============================================================================
// USER & PROFILE API TYPES
// ============================================================================

export interface UserProfile {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserRole;
  organizationId: string;
  phoneNumber?: string;
  avatarUrl?: string;
  isActive: boolean;
  isMfaEnabled: boolean;
  lastLoginAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FIRM_ADMIN = 'FIRM_ADMIN',
  ATTORNEY = 'ATTORNEY',
  PARALEGAL = 'PARALEGAL',
  LEGAL_ASSISTANT = 'LEGAL_ASSISTANT',
  CLIENT = 'CLIENT',
  BILLING_MANAGER = 'BILLING_MANAGER',
  GUEST = 'GUEST',
}

export interface UpdateProfileRequest {
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  avatarUrl?: string;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

// ============================================================================
// CASE MANAGEMENT API TYPES
// ============================================================================

export interface CaseListResponse {
  cases: CaseItem[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface CaseItem {
  id: string;
  caseNumber: string;
  title: string;
  status: CaseStatus;
  caseType: string;
  clientId: string;
  clientName: string;
  assignedAttorneyId: string;
  assignedAttorneyName: string;
  filingDate: Date;
  trialDate?: Date;
  courtName?: string;
  jurisdiction?: string;
  estimatedValue?: number;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  lastActivity: Date;
  createdAt: Date;
  updatedAt: Date;
}

export enum CaseStatus {
  INTAKE = 'INTAKE',
  ACTIVE = 'ACTIVE',
  DISCOVERY = 'DISCOVERY',
  TRIAL = 'TRIAL',
  SETTLEMENT = 'SETTLEMENT',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export interface CreateCaseRequest {
  caseNumber: string;
  title: string;
  caseType: string;
  clientId: string;
  assignedAttorneyId: string;
  filingDate: Date;
  description?: string;
  courtName?: string;
  jurisdiction?: string;
  estimatedValue?: number;
}

export interface UpdateCaseRequest {
  title?: string;
  status?: CaseStatus;
  caseType?: string;
  assignedAttorneyId?: string;
  trialDate?: Date;
  courtName?: string;
  jurisdiction?: string;
  estimatedValue?: number;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
}

export interface CaseDetailsResponse extends CaseItem {
  description: string;
  parties: PartyItem[];
  team: TeamMember[];
  phases: CasePhase[];
  documents: DocumentSummary[];
  recentActivity: ActivityItem[];
}

// ============================================================================
// DOCUMENT MANAGEMENT API TYPES
// ============================================================================

export interface DocumentListResponse {
  documents: DocumentItem[];
  total: number;
  page: number;
  pageSize: number;
}

export interface DocumentItem {
  id: string;
  title: string;
  documentType: string;
  caseId?: string;
  caseName?: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
  status: DocumentStatus;
  uploadedBy: string;
  uploadedByName: string;
  uploadedAt: Date;
  tags: string[];
  version: number;
  isConfidential: boolean;
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
  ARCHIVED = 'ARCHIVED',
}

export interface UploadDocumentRequest {
  file: File;
  title: string;
  documentType: string;
  caseId?: string;
  isConfidential?: boolean;
  tags?: string[];
}

export interface DocumentDetailsResponse extends DocumentItem {
  description?: string;
  storagePath: string;
  ocrStatus?: string;
  extractedText?: string;
  metadata: Record<string, any>;
  versions: DocumentVersion[];
  accessLog: AccessLogEntry[];
}

export interface DocumentVersion {
  id: string;
  version: number;
  uploadedBy: string;
  uploadedAt: Date;
  changeNote?: string;
  fileSize: number;
}

// ============================================================================
// BILLING API TYPES
// ============================================================================

export interface TimeEntryListResponse {
  entries: TimeEntryItem[];
  total: number;
  totalHours: number;
  totalAmount: number;
}

export interface TimeEntryItem {
  id: string;
  caseId: string;
  caseName: string;
  userId: string;
  userName: string;
  date: Date;
  hours: number;
  rate: number;
  amount: number;
  description: string;
  isBillable: boolean;
  status: 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'INVOICED';
  createdAt: Date;
}

export interface CreateTimeEntryRequest {
  caseId: string;
  date: Date;
  hours: number;
  description: string;
  isBillable?: boolean;
  taskType?: string;
}

export interface InvoiceListResponse {
  invoices: InvoiceItem[];
  total: number;
  totalAmount: number;
}

export interface InvoiceItem {
  id: string;
  invoiceNumber: string;
  caseId: string;
  caseName: string;
  clientId: string;
  clientName: string;
  issueDate: Date;
  dueDate: Date;
  totalAmount: number;
  paidAmount: number;
  status: 'DRAFT' | 'SENT' | 'PAID' | 'OVERDUE' | 'CANCELLED';
  createdAt: Date;
}

export interface InvoiceDetailsResponse extends InvoiceItem {
  lineItems: InvoiceLineItem[];
  payments: PaymentItem[];
}

export interface InvoiceLineItem {
  id: string;
  description: string;
  quantity: number;
  rate: number;
  amount: number;
  type: 'TIME' | 'EXPENSE' | 'FIXED_FEE';
}

export interface PaymentItem {
  id: string;
  amount: number;
  paymentDate: Date;
  paymentMethod: string;
  reference?: string;
}

// ============================================================================
// DISCOVERY API TYPES
// ============================================================================

export interface DiscoveryRequestListResponse {
  requests: DiscoveryRequestItem[];
  total: number;
}

export interface DiscoveryRequestItem {
  id: string;
  caseId: string;
  caseName: string;
  requestType: 'INTERROGATORY' | 'DOCUMENT' | 'ADMISSION' | 'DEPOSITION';
  requestNumber: string;
  propoundedBy: string;
  propoundedTo: string;
  propoundedDate: Date;
  dueDate: Date;
  status: 'PENDING' | 'IN_PROGRESS' | 'RESPONDED' | 'OVERDUE';
  responseDate?: Date;
  createdAt: Date;
}

export interface DepositionItem {
  id: string;
  caseId: string;
  witnessName: string;
  depositionDate: Date;
  location: string;
  status: 'SCHEDULED' | 'COMPLETED' | 'CANCELLED';
  transcript?: string;
  videographer?: string;
  courtReporter?: string;
}

// ============================================================================
// ANALYTICS API TYPES
// ============================================================================

export interface DashboardStatsResponse {
  totalCases: number;
  activeCases: number;
  upcomingDeadlines: number;
  overdueItems: number;
  totalBillableHours: number;
  totalRevenue: number;
  casesByStatus: Record<string, number>;
  revenueByMonth: MonthlyRevenue[];
  topCasesByActivity: CaseActivity[];
}

export interface MonthlyRevenue {
  month: string;
  revenue: number;
  billableHours: number;
}

export interface CaseActivity {
  caseId: string;
  caseName: string;
  activityCount: number;
  lastActivity: Date;
}

// ============================================================================
// SEARCH API TYPES
// ============================================================================

export interface SearchRequest {
  query: string;
  filters?: SearchFilters;
  page?: number;
  pageSize?: number;
}

export interface SearchFilters {
  caseId?: string;
  documentType?: string;
  dateFrom?: Date;
  dateTo?: Date;
  tags?: string[];
  status?: string;
}

export interface SearchResponse {
  results: SearchResult[];
  total: number;
  facets: SearchFacets;
  took: number;
}

export interface SearchResult {
  id: string;
  type: 'CASE' | 'DOCUMENT' | 'CLIENT' | 'CONTACT';
  title: string;
  description?: string;
  highlights: string[];
  score: number;
  metadata: Record<string, any>;
}

export interface SearchFacets {
  types: Record<string, number>;
  statuses: Record<string, number>;
  dateRanges: Record<string, number>;
}

// ============================================================================
// NOTIFICATION API TYPES
// ============================================================================

export interface NotificationListResponse {
  notifications: NotificationItem[];
  unreadCount: number;
  total: number;
}

export interface NotificationItem {
  id: string;
  type: NotificationType;
  title: string;
  message: string;
  isRead: boolean;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  actionUrl?: string;
  metadata?: Record<string, any>;
  createdAt: Date;
}

export enum NotificationType {
  CASE_ASSIGNED = 'CASE_ASSIGNED',
  DEADLINE_APPROACHING = 'DEADLINE_APPROACHING',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  INVOICE_GENERATED = 'INVOICE_GENERATED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

// ============================================================================
// COMMON API TYPES
// ============================================================================

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message?: string;
  timestamp: Date;
}

export interface ApiError {
  success: false;
  error: string;
  message: string;
  statusCode: number;
  timestamp: Date;
  path?: string;
  details?: any;
}

export interface PaginationParams {
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: 'ASC' | 'DESC';
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

// ============================================================================
// HELPER TYPES
// ============================================================================

export interface PartyItem {
  id: string;
  name: string;
  role: 'PLAINTIFF' | 'DEFENDANT' | 'THIRD_PARTY';
  contactInfo?: string;
}

export interface TeamMember {
  id: string;
  userId: string;
  name: string;
  role: string;
  assignedDate: Date;
}

export interface CasePhase {
  id: string;
  name: string;
  status: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
  startDate?: Date;
  endDate?: Date;
}

export interface DocumentSummary {
  id: string;
  title: string;
  type: string;
  uploadedAt: Date;
}

export interface ActivityItem {
  id: string;
  type: string;
  description: string;
  userId: string;
  userName: string;
  timestamp: Date;
}

export interface AccessLogEntry {
  id: string;
  userId: string;
  userName: string;
  action: 'VIEW' | 'DOWNLOAD' | 'EDIT' | 'DELETE';
  timestamp: Date;
  ipAddress?: string;
}
