import { DataSource } from 'typeorm';
import { Client } from '@core/clients/entities/client.entity';

export async function seedClients(dataSource: DataSource): Promise<void> {
  const clientRepository = dataSource.getRepository(Client);

  // Check if clients already exist
  const existingClients = await clientRepository.count();
  if (existingClients > 0) {
    console.log('Clients already seeded, skipping...');
    return;
  }

  const clients = [
    {
      clientNumber: 'CLT-001',
      name: 'Acme Corporation',
      clientType: 'corporation',
      status: 'active',
      email: 'legal@acmecorp.com',
      phone: '555-1000',
      website: 'https://www.acmecorp.com',
      address: '123 Business Ave, Suite 500',
      city: 'San Francisco',
      state: 'California',
      zipCode: '94102',
      country: 'USA',
      billingAddress: '123 Business Ave, Suite 500',
      billingCity: 'San Francisco',
      billingState: 'California',
      billingZipCode: '94102',
      billingCountry: 'USA',
      taxId: '12-3456789',
      industry: 'Technology',
      primaryContactName: 'Robert Johnson',
      primaryContactEmail: 'rjohnson@acmecorp.com',
      primaryContactPhone: '555-1001',
      primaryContactTitle: 'General Counsel',
      clientSince: new Date('2020-01-15'),
      paymentTerms: 'net_30',
      creditLimit: 500000,
      isVip: true,
      tags: ['technology', 'fortune500', 'vip'],
    },
    {
      clientNumber: 'CLT-002',
      name: 'Global Manufacturing Inc.',
      clientType: 'corporation',
      status: 'active',
      email: 'legal@globalmanufacturing.com',
      phone: '555-2000',
      website: 'https://www.globalmanufacturing.com',
      address: '456 Industrial Blvd',
      city: 'Los Angeles',
      state: 'California',
      zipCode: '90001',
      country: 'USA',
      billingAddress: '456 Industrial Blvd',
      billingCity: 'Los Angeles',
      billingState: 'California',
      billingZipCode: '90001',
      billingCountry: 'USA',
      taxId: '23-4567890',
      industry: 'Manufacturing',
      primaryContactName: 'Lisa Anderson',
      primaryContactEmail: 'landerson@globalmanufacturing.com',
      primaryContactPhone: '555-2001',
      primaryContactTitle: 'VP Legal',
      clientSince: new Date('2019-06-01'),
      paymentTerms: 'net_45',
      creditLimit: 250000,
      tags: ['manufacturing', 'international'],
    },
    {
      clientNumber: 'CLT-003',
      name: 'John Smith',
      clientType: 'individual',
      status: 'active',
      email: 'jsmith@email.com',
      phone: '555-3000',
      address: '789 Residential St',
      city: 'San Diego',
      state: 'California',
      zipCode: '92101',
      country: 'USA',
      billingAddress: '789 Residential St',
      billingCity: 'San Diego',
      billingState: 'California',
      billingZipCode: '92101',
      billingCountry: 'USA',
      primaryContactName: 'John Smith',
      primaryContactEmail: 'jsmith@email.com',
      primaryContactPhone: '555-3000',
      clientSince: new Date('2022-03-15'),
      paymentTerms: 'net_30',
      creditLimit: 50000,
      tags: ['individual', 'personal-injury'],
    },
    {
      clientNumber: 'CLT-004',
      name: 'Tech Startup LLC',
      clientType: 'llc',
      status: 'active',
      email: 'founders@techstartup.io',
      phone: '555-4000',
      website: 'https://www.techstartup.io',
      address: '321 Innovation Dr',
      city: 'San Jose',
      state: 'California',
      zipCode: '95110',
      country: 'USA',
      billingAddress: '321 Innovation Dr',
      billingCity: 'San Jose',
      billingState: 'California',
      billingZipCode: '95110',
      billingCountry: 'USA',
      taxId: '34-5678901',
      industry: 'Software',
      primaryContactName: 'Alex Chen',
      primaryContactEmail: 'achen@techstartup.io',
      primaryContactPhone: '555-4001',
      primaryContactTitle: 'Co-Founder & CEO',
      clientSince: new Date('2023-01-10'),
      paymentTerms: 'net_15',
      creditLimit: 100000,
      hasRetainer: true,
      retainerAmount: 25000,
      retainerBalance: 15000,
      tags: ['startup', 'technology', 'venture-backed'],
    },
    {
      clientNumber: 'CLT-005',
      name: 'Community Foundation',
      clientType: 'nonprofit',
      status: 'active',
      email: 'legal@communityfoundation.org',
      phone: '555-5000',
      website: 'https://www.communityfoundation.org',
      address: '555 Charity Lane',
      city: 'Sacramento',
      state: 'California',
      zipCode: '95814',
      country: 'USA',
      billingAddress: '555 Charity Lane',
      billingCity: 'Sacramento',
      billingState: 'California',
      billingZipCode: '95814',
      billingCountry: 'USA',
      taxId: '45-6789012',
      industry: 'Nonprofit',
      primaryContactName: 'Maria Garcia',
      primaryContactEmail: 'mgarcia@communityfoundation.org',
      primaryContactPhone: '555-5001',
      primaryContactTitle: 'Executive Director',
      clientSince: new Date('2021-09-01'),
      paymentTerms: 'net_60',
      creditLimit: 75000,
      tags: ['nonprofit', 'charitable', '501c3'],
    },
  ];

  for (const clientData of clients) {
    const client = clientRepository.create(clientData);
    await clientRepository.save(client);
  }

  console.log('✅ Clients seeded successfully');
}
