import { useTheme } from "@/hooks/useTheme";
import { cn } from '@/lib/cn';
import { TypewriterText } from '@/components/atoms/TypewriterText';
import { Card } from '@/components/molecules/Card/Card';
import { ResearchSession } from '@/types';
import { Bookmark, BookOpen, Share2, ThumbsDown, ThumbsUp } from 'lucide-react';
import { ResearchResultCard } from './ResearchResultCard';

interface ResearchResultsProps {
    session?: ResearchSession;
    onViewSource?: (url: string, title: string) => void;
}

export function ResearchResults({ session, onViewSource }: ResearchResultsProps) {
    const { theme } = useTheme();

    if (!session) {
        return (
            <div className={cn("flex flex-col items-center justify-center h-full opacity-60", theme.text.tertiary)}>
                <BookOpen className="h-16 w-16 mb-4" />
                <p className="text-lg font-medium">Enter a legal query to begin research</p>
            </div>
        );
    }

    return (
        <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h3 className={cn("text-lg font-bold leading-snug", theme.text.primary)}>{session.query}</h3>
                    <p className={cn("text-xs mt-1", theme.text.secondary)}>Generated by LexiFlow AI • Grounded via Google Search</p>
                </div>
                <div className="flex gap-2">
                    <button className={cn("p-2 border rounded transition-colors", theme.surface.default, theme.border.default, theme.text.secondary, `hover:${theme.surface.highlight}`)}><Bookmark className="h-4 w-4" /></button>
                    <button className={cn("p-2 border rounded transition-colors", theme.surface.default, theme.border.default, theme.text.secondary, `hover:${theme.surface.highlight}`)}><Share2 className="h-4 w-4" /></button>
                </div>
            </div>

            <Card className={cn("shadow-md", theme.primary.border)}>
                <TypewriterText text={session.response} />

                <div className={cn("mt-6 flex items-center justify-end space-x-4 border-t pt-4", theme.border.default)}>
                    <span className={cn("text-xs", theme.text.tertiary)}>Was this answer helpful?</span>
                    <button className={cn("p-1.5 rounded transition-colors hover:bg-green-50 hover:text-green-600", theme.text.tertiary)}><ThumbsUp className="h-4 w-4" /></button>
                    <button className={cn("p-1.5 rounded transition-colors hover:bg-red-50 hover:text-red-600", theme.text.tertiary)}><ThumbsDown className="h-4 w-4" /></button>
                </div>
            </Card>

            {session?.sources?.length > 0 && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-700 delay-300 fill-mode-backwards">
                    <h4 className={cn("text-xs font-bold uppercase tracking-wider mb-3 ml-1", theme.text.secondary)}>Authorities Cited</h4>
                    <div className="grid grid-cols-1 gap-3">
                        {session?.sources?.map((source, idx) => (
                            <ResearchResultCard
                                key={idx}
                                source={source}
                                onView={() => onViewSource && source.url && onViewSource(source.url, source.title)}
                            />
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};
