/**
 * @module components/enterprise/CRM/BusinessDevelopment/constants
 * @description Static data and configuration for Business Development module
 */

import { BarChart3, FileText, Target, Users } from "lucide-react";
import type { Lead, Pitch, RFP, WinLossAnalysis } from "./types";

export const TABS = [
  { id: "leads" as const, label: "Leads", icon: Users },
  { id: "pitches" as const, label: "Pitches", icon: Target },
  { id: "rfps" as const, label: "RFPs", icon: FileText },
  { id: "analysis" as const, label: "Win/Loss Analysis", icon: BarChart3 },
] as const;

export const MOCK_LEADS: Lead[] = [
  {
    id: "1",
    name: "Sarah Chen",
    company: "TechVentures Inc.",
    industry: "Technology",
    email: "sarah.chen@techventures.com",
    phone: "555-0123",
    source: "Referral",
    status: "Proposal",
    practiceArea: "Corporate Law",
    estimatedValue: 450000,
    probability: 75,
    assignedTo: "John Smith",
    createdDate: "2025-12-15",
    lastActivity: "2026-01-02",
    nextAction: "Send revised proposal",
    nextActionDate: "2026-01-05",
  },
  {
    id: "2",
    name: "Michael Rodriguez",
    company: "BioHealth Solutions",
    industry: "Healthcare",
    email: "m.rodriguez@biohealth.com",
    phone: "555-0456",
    source: "Conference",
    status: "Qualified",
    practiceArea: "IP Litigation",
    estimatedValue: 320000,
    probability: 60,
    assignedTo: "Sarah Johnson",
    createdDate: "2025-12-20",
    lastActivity: "2026-01-01",
    nextAction: "Schedule initial consultation",
    nextActionDate: "2026-01-08",
  },
  {
    id: "3",
    name: "Emma Wilson",
    company: "Global Manufacturing LLC",
    industry: "Manufacturing",
    email: "ewilson@globalmanuf.com",
    phone: "555-0789",
    source: "Website",
    status: "Won",
    practiceArea: "Employment Law",
    estimatedValue: 180000,
    probability: 100,
    assignedTo: "Mike Wilson",
    createdDate: "2025-11-10",
    lastActivity: "2025-12-28",
    notes: "Signed engagement letter on 12/28",
  },
];

export const MOCK_PITCHES: Pitch[] = [
  {
    id: "1",
    leadId: "1",
    clientName: "TechVentures Inc.",
    practiceArea: "Corporate Law",
    pitchDate: "2025-12-18",
    pitchType: "In-Person",
    attendees: ["Sarah Chen", "CFO", "General Counsel"],
    presenters: ["John Smith", "Senior Partner"],
    status: "Completed",
    followUpDate: "2026-01-05",
    estimatedValue: 450000,
    outcome: "No Decision Yet",
    feedbackReceived: true,
    notes: "Very positive reception, requested revised scope",
  },
  {
    id: "2",
    leadId: "4",
    clientName: "RetailCorp",
    practiceArea: "Real Estate",
    pitchDate: "2026-01-15",
    pitchType: "Virtual",
    attendees: ["CEO", "VP Operations"],
    presenters: ["Jane Davis", "Associate"],
    status: "Scheduled",
    estimatedValue: 280000,
  },
];

export const MOCK_RFPS: RFP[] = [
  {
    id: "1",
    title: "Outside General Counsel Services",
    clientName: "Acme Corporation",
    industry: "Technology",
    practiceArea: "Corporate Law",
    receivedDate: "2025-12-10",
    dueDate: "2026-01-20",
    estimatedValue: 850000,
    status: "In Progress",
    teamLead: "John Smith",
    contributors: ["Sarah Johnson", "Mike Wilson", "Jane Davis"],
    progress: 65,
    sections: [
      {
        name: "Executive Summary",
        assignedTo: "John Smith",
        status: "Complete",
      },
      {
        name: "Firm Overview",
        assignedTo: "Sarah Johnson",
        status: "Complete",
      },
      {
        name: "Practice Area Experience",
        assignedTo: "Mike Wilson",
        status: "In Progress",
      },
      { name: "Team Bios", assignedTo: "Jane Davis", status: "Review" },
      { name: "Pricing", assignedTo: "John Smith", status: "Not Started" },
    ],
    questions: 45,
    pageLimit: 50,
    goNoGoDecision: "Go",
    goNoGoReason: "Strong fit, existing relationship, high value",
  },
  {
    id: "2",
    title: "IP Litigation Panel",
    clientName: "Tech Innovations LLC",
    industry: "Technology",
    practiceArea: "IP Litigation",
    receivedDate: "2026-01-05",
    dueDate: "2026-02-15",
    estimatedValue: 500000,
    status: "Go/No-Go",
    teamLead: "Sarah Johnson",
    contributors: [],
    progress: 5,
    sections: [],
    questions: 30,
    pageLimit: 30,
    goNoGoDecision: "Pending",
  },
];

export const MOCK_WIN_LOSS_DATA: WinLossAnalysis[] = [
  {
    id: "1",
    opportunityName: "Global Manufacturing Employment Matter",
    clientName: "Global Manufacturing LLC",
    practiceArea: "Employment Law",
    estimatedValue: 180000,
    actualValue: 180000,
    outcome: "Won",
    closeDate: "2025-12-28",
    winReasons: [
      "Strong industry expertise",
      "Competitive pricing",
      "Responsive proposal",
    ],
    lessonsLearned: [
      "Quick turnaround on proposal was key",
      "Industry-specific case studies resonated",
    ],
    teamMembers: ["Mike Wilson", "Jane Davis"],
    salesCycle: 48,
  },
  {
    id: "2",
    opportunityName: "Financial Services Compliance Review",
    clientName: "BigBank Corp",
    practiceArea: "Compliance",
    estimatedValue: 400000,
    outcome: "Lost",
    closeDate: "2025-12-15",
    lossReasons: [
      "Price too high",
      "Competitor had existing relationship",
      "Insufficient fintech experience",
    ],
    competitorWon: "Smith & Associates",
    lessonsLearned: [
      "Need more fintech expertise on team",
      "Consider flexible pricing for large engagements",
    ],
    teamMembers: ["John Smith", "Sarah Johnson"],
    salesCycle: 62,
  },
];

export const ANALYTICS_DATA = {
  leadsByStatus: [
    { status: "New", count: 12, value: 850000 },
    { status: "Contacted", count: 8, value: 620000 },
    { status: "Qualified", count: 15, value: 1250000 },
    { status: "Proposal", count: 6, value: 980000 },
    { status: "Negotiation", count: 4, value: 720000 },
    { status: "Won", count: 22, value: 3200000 },
    { status: "Lost", count: 18, value: 1100000 },
  ],
  leadsBySource: [
    { source: "Referral", count: 28, color: "#3b82f6" },
    { source: "Website", count: 15, color: "#10b981" },
    { source: "Conference", count: 12, color: "#f59e0b" },
    { source: "LinkedIn", count: 8, color: "#8b5cf6" },
    { source: "Cold Outreach", count: 5, color: "#ef4444" },
    { source: "Other", count: 7, color: "#6b7280" },
  ],
  conversionTrend: [
    { month: "Jul", leads: 42, won: 8, lost: 12 },
    { month: "Aug", leads: 45, won: 10, lost: 10 },
    { month: "Sep", leads: 38, won: 7, lost: 9 },
    { month: "Oct", leads: 52, won: 12, lost: 14 },
    { month: "Nov", leads: 48, won: 11, lost: 11 },
    { month: "Dec", leads: 55, won: 15, lost: 13 },
  ],
};
