// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/cases": {
    params: {};
  };
  "/cases/create": {
    params: {};
  };
  "/cases/:caseId": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/overview": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/calendar": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/analytics": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/operations": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/insights": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/financials": {
    params: {
      "caseId": string;
    };
  };
  "/docket": {
    params: {};
  };
  "/docket/:docketId": {
    params: {
      "docketId": string;
    };
  };
  "/documents": {
    params: {};
  };
  "/documents/:documentId": {
    params: {
      "documentId": string;
    };
  };
  "/correspondence": {
    params: {};
  };
  "/correspondence/compose": {
    params: {};
  };
  "/workflows": {
    params: {};
  };
  "/workflows/:workflowId": {
    params: {
      "workflowId": string;
    };
  };
  "/discovery": {
    params: {};
  };
  "/discovery/:discoveryId": {
    params: {
      "discoveryId": string;
    };
  };
  "/evidence": {
    params: {};
  };
  "/evidence/:evidenceId": {
    params: {
      "evidenceId": string;
    };
  };
  "/exhibits": {
    params: {};
  };
  "/exhibits/:exhibitId": {
    params: {
      "exhibitId": string;
    };
  };
  "/research": {
    params: {};
  };
  "/research/:researchId": {
    params: {
      "researchId": string;
    };
  };
  "/citations": {
    params: {};
  };
  "/war_room": {
    params: {};
  };
  "/war_room/:roomId": {
    params: {
      "roomId": string;
    };
  };
  "/pleading_builder": {
    params: {};
  };
  "/drafting": {
    params: {};
  };
  "/litigation_builder": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/crm": {
    params: {};
  };
  "/crm/:clientId": {
    params: {
      "clientId": string;
    };
  };
  "/compliance": {
    params: {};
  };
  "/practice": {
    params: {};
  };
  "/daf": {
    params: {};
  };
  "/entities": {
    params: {};
  };
  "/data_platform": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/library": {
    params: {};
  };
  "/clauses": {
    params: {};
  };
  "/jurisdiction": {
    params: {};
  };
  "/rules_engine": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/theme-settings": {
    params: {};
  };
  "/real_estate/portfolio_summary": {
    params: {};
  };
  "/real_estate/inventory": {
    params: {};
  };
  "/real_estate/utilization": {
    params: {};
  };
  "/real_estate/outgrants": {
    params: {};
  };
  "/real_estate/solicitations": {
    params: {};
  };
  "/real_estate/relocation": {
    params: {};
  };
  "/real_estate/cost_share": {
    params: {};
  };
  "/real_estate/disposal": {
    params: {};
  };
  "/real_estate/acquisition": {
    params: {};
  };
  "/real_estate/encroachment": {
    params: {};
  };
  "/real_estate/user_management": {
    params: {};
  };
  "/real_estate/audit_readiness": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/dashboard" | "/cases" | "/cases/create" | "/cases/:caseId" | "/cases/:caseId/overview" | "/cases/:caseId/calendar" | "/cases/:caseId/analytics" | "/cases/:caseId/operations" | "/cases/:caseId/insights" | "/cases/:caseId/financials" | "/docket" | "/docket/:docketId" | "/documents" | "/documents/:documentId" | "/correspondence" | "/correspondence/compose" | "/workflows" | "/workflows/:workflowId" | "/discovery" | "/discovery/:discoveryId" | "/evidence" | "/evidence/:evidenceId" | "/exhibits" | "/exhibits/:exhibitId" | "/research" | "/research/:researchId" | "/citations" | "/war_room" | "/war_room/:roomId" | "/pleading_builder" | "/drafting" | "/litigation_builder" | "/billing" | "/crm" | "/crm/:clientId" | "/compliance" | "/practice" | "/daf" | "/entities" | "/data_platform" | "/analytics" | "/library" | "/clauses" | "/jurisdiction" | "/rules_engine" | "/calendar" | "/messages" | "/profile" | "/admin" | "/admin/theme-settings" | "/real_estate/portfolio_summary" | "/real_estate/inventory" | "/real_estate/utilization" | "/real_estate/outgrants" | "/real_estate/solicitations" | "/real_estate/relocation" | "/real_estate/cost_share" | "/real_estate/disposal" | "/real_estate/acquisition" | "/real_estate/encroachment" | "/real_estate/user_management" | "/real_estate/audit_readiness";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/dashboard" | "/cases" | "/cases/create" | "/cases/:caseId" | "/cases/:caseId/overview" | "/cases/:caseId/calendar" | "/cases/:caseId/analytics" | "/cases/:caseId/operations" | "/cases/:caseId/insights" | "/cases/:caseId/financials" | "/docket" | "/docket/:docketId" | "/documents" | "/documents/:documentId" | "/correspondence" | "/correspondence/compose" | "/workflows" | "/workflows/:workflowId" | "/discovery" | "/discovery/:discoveryId" | "/evidence" | "/evidence/:evidenceId" | "/exhibits" | "/exhibits/:exhibitId" | "/research" | "/research/:researchId" | "/citations" | "/war_room" | "/war_room/:roomId" | "/pleading_builder" | "/drafting" | "/litigation_builder" | "/billing" | "/crm" | "/crm/:clientId" | "/compliance" | "/practice" | "/daf" | "/entities" | "/data_platform" | "/analytics" | "/library" | "/clauses" | "/jurisdiction" | "/rules_engine" | "/calendar" | "/messages" | "/profile" | "/admin" | "/admin/theme-settings" | "/real_estate/portfolio_summary" | "/real_estate/inventory" | "/real_estate/utilization" | "/real_estate/outgrants" | "/real_estate/solicitations" | "/real_estate/relocation" | "/real_estate/cost_share" | "/real_estate/disposal" | "/real_estate/acquisition" | "/real_estate/encroachment" | "/real_estate/user_management" | "/real_estate/audit_readiness";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/cases/index.tsx": {
    id: "routes/cases/index";
    page: "/cases";
  };
  "routes/cases/create.tsx": {
    id: "routes/cases/create";
    page: "/cases/create";
  };
  "routes/cases/case-detail.tsx": {
    id: "routes/cases/case-detail";
    page: "/cases/:caseId";
  };
  "routes/cases/overview.tsx": {
    id: "routes/cases/overview";
    page: "/cases/:caseId/overview";
  };
  "routes/cases/calendar.tsx": {
    id: "routes/cases/calendar";
    page: "/cases/:caseId/calendar";
  };
  "routes/cases/analytics.tsx": {
    id: "routes/cases/analytics";
    page: "/cases/:caseId/analytics";
  };
  "routes/cases/operations.tsx": {
    id: "routes/cases/operations";
    page: "/cases/:caseId/operations";
  };
  "routes/cases/insights.tsx": {
    id: "routes/cases/insights";
    page: "/cases/:caseId/insights";
  };
  "routes/cases/financials.tsx": {
    id: "routes/cases/financials";
    page: "/cases/:caseId/financials";
  };
  "routes/docket/index.tsx": {
    id: "routes/docket/index";
    page: "/docket";
  };
  "routes/docket/detail.tsx": {
    id: "routes/docket/detail";
    page: "/docket/:docketId";
  };
  "routes/documents/index.tsx": {
    id: "routes/documents/index";
    page: "/documents";
  };
  "routes/documents/detail.tsx": {
    id: "routes/documents/detail";
    page: "/documents/:documentId";
  };
  "routes/correspondence/index.tsx": {
    id: "routes/correspondence/index";
    page: "/correspondence";
  };
  "routes/correspondence/compose.tsx": {
    id: "routes/correspondence/compose";
    page: "/correspondence/compose";
  };
  "routes/workflows/index.tsx": {
    id: "routes/workflows/index";
    page: "/workflows";
  };
  "routes/workflows/detail.tsx": {
    id: "routes/workflows/detail";
    page: "/workflows/:workflowId";
  };
  "routes/discovery/index.tsx": {
    id: "routes/discovery/index";
    page: "/discovery";
  };
  "routes/discovery/detail.tsx": {
    id: "routes/discovery/detail";
    page: "/discovery/:discoveryId";
  };
  "routes/evidence/index.tsx": {
    id: "routes/evidence/index";
    page: "/evidence";
  };
  "routes/evidence/detail.tsx": {
    id: "routes/evidence/detail";
    page: "/evidence/:evidenceId";
  };
  "routes/exhibits/index.tsx": {
    id: "routes/exhibits/index";
    page: "/exhibits";
  };
  "routes/exhibits/detail.tsx": {
    id: "routes/exhibits/detail";
    page: "/exhibits/:exhibitId";
  };
  "routes/research/index.tsx": {
    id: "routes/research/index";
    page: "/research";
  };
  "routes/research/detail.tsx": {
    id: "routes/research/detail";
    page: "/research/:researchId";
  };
  "routes/citations/index.tsx": {
    id: "routes/citations/index";
    page: "/citations";
  };
  "routes/war-room/index.tsx": {
    id: "routes/war-room/index";
    page: "/war_room";
  };
  "routes/war-room/detail.tsx": {
    id: "routes/war-room/detail";
    page: "/war_room/:roomId";
  };
  "routes/pleading/builder.tsx": {
    id: "routes/pleading/builder";
    page: "/pleading_builder";
  };
  "routes/drafting/index.tsx": {
    id: "routes/drafting/index";
    page: "/drafting";
  };
  "routes/litigation/builder.tsx": {
    id: "routes/litigation/builder";
    page: "/litigation_builder";
  };
  "routes/billing/index.tsx": {
    id: "routes/billing/index";
    page: "/billing";
  };
  "routes/crm/index.tsx": {
    id: "routes/crm/index";
    page: "/crm";
  };
  "routes/crm/client-detail.tsx": {
    id: "routes/crm/client-detail";
    page: "/crm/:clientId";
  };
  "routes/compliance/index.tsx": {
    id: "routes/compliance/index";
    page: "/compliance";
  };
  "routes/practice/index.tsx": {
    id: "routes/practice/index";
    page: "/practice";
  };
  "routes/daf/index.tsx": {
    id: "routes/daf/index";
    page: "/daf";
  };
  "routes/entities/index.tsx": {
    id: "routes/entities/index";
    page: "/entities";
  };
  "routes/data-platform/index.tsx": {
    id: "routes/data-platform/index";
    page: "/data_platform";
  };
  "routes/analytics/index.tsx": {
    id: "routes/analytics/index";
    page: "/analytics";
  };
  "routes/library/index.tsx": {
    id: "routes/library/index";
    page: "/library";
  };
  "routes/clauses/index.tsx": {
    id: "routes/clauses/index";
    page: "/clauses";
  };
  "routes/jurisdiction/index.tsx": {
    id: "routes/jurisdiction/index";
    page: "/jurisdiction";
  };
  "routes/rules/index.tsx": {
    id: "routes/rules/index";
    page: "/rules_engine";
  };
  "routes/calendar/index.tsx": {
    id: "routes/calendar/index";
    page: "/calendar";
  };
  "routes/messages/index.tsx": {
    id: "routes/messages/index";
    page: "/messages";
  };
  "routes/profile/index.tsx": {
    id: "routes/profile/index";
    page: "/profile";
  };
  "routes/admin/index.tsx": {
    id: "routes/admin/index";
    page: "/admin";
  };
  "routes/admin/theme-settings.tsx": {
    id: "routes/admin/theme-settings";
    page: "/admin/theme-settings";
  };
  "routes/real-estate/portfolio-summary.tsx": {
    id: "routes/real-estate/portfolio-summary";
    page: "/real_estate/portfolio_summary";
  };
  "routes/real-estate/inventory.tsx": {
    id: "routes/real-estate/inventory";
    page: "/real_estate/inventory";
  };
  "routes/real-estate/utilization.tsx": {
    id: "routes/real-estate/utilization";
    page: "/real_estate/utilization";
  };
  "routes/real-estate/outgrants.tsx": {
    id: "routes/real-estate/outgrants";
    page: "/real_estate/outgrants";
  };
  "routes/real-estate/solicitations.tsx": {
    id: "routes/real-estate/solicitations";
    page: "/real_estate/solicitations";
  };
  "routes/real-estate/relocation.tsx": {
    id: "routes/real-estate/relocation";
    page: "/real_estate/relocation";
  };
  "routes/real-estate/cost-share.tsx": {
    id: "routes/real-estate/cost-share";
    page: "/real_estate/cost_share";
  };
  "routes/real-estate/disposal.tsx": {
    id: "routes/real-estate/disposal";
    page: "/real_estate/disposal";
  };
  "routes/real-estate/acquisition.tsx": {
    id: "routes/real-estate/acquisition";
    page: "/real_estate/acquisition";
  };
  "routes/real-estate/encroachment.tsx": {
    id: "routes/real-estate/encroachment";
    page: "/real_estate/encroachment";
  };
  "routes/real-estate/user-management.tsx": {
    id: "routes/real-estate/user-management";
    page: "/real_estate/user_management";
  };
  "routes/real-estate/audit-readiness.tsx": {
    id: "routes/real-estate/audit-readiness";
    page: "/real_estate/audit_readiness";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/auth/login": typeof import("./src/routes/auth/login.tsx");
  "routes/layout": typeof import("./src/routes/layout.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/cases/index": typeof import("./src/routes/cases/index.tsx");
  "routes/cases/create": typeof import("./src/routes/cases/create.tsx");
  "routes/cases/case-detail": typeof import("./src/routes/cases/case-detail.tsx");
  "routes/cases/overview": typeof import("./src/routes/cases/overview.tsx");
  "routes/cases/calendar": typeof import("./src/routes/cases/calendar.tsx");
  "routes/cases/analytics": typeof import("./src/routes/cases/analytics.tsx");
  "routes/cases/operations": typeof import("./src/routes/cases/operations.tsx");
  "routes/cases/insights": typeof import("./src/routes/cases/insights.tsx");
  "routes/cases/financials": typeof import("./src/routes/cases/financials.tsx");
  "routes/docket/index": typeof import("./src/routes/docket/index.tsx");
  "routes/docket/detail": typeof import("./src/routes/docket/detail.tsx");
  "routes/documents/index": typeof import("./src/routes/documents/index.tsx");
  "routes/documents/detail": typeof import("./src/routes/documents/detail.tsx");
  "routes/correspondence/index": typeof import("./src/routes/correspondence/index.tsx");
  "routes/correspondence/compose": typeof import("./src/routes/correspondence/compose.tsx");
  "routes/workflows/index": typeof import("./src/routes/workflows/index.tsx");
  "routes/workflows/detail": typeof import("./src/routes/workflows/detail.tsx");
  "routes/discovery/index": typeof import("./src/routes/discovery/index.tsx");
  "routes/discovery/detail": typeof import("./src/routes/discovery/detail.tsx");
  "routes/evidence/index": typeof import("./src/routes/evidence/index.tsx");
  "routes/evidence/detail": typeof import("./src/routes/evidence/detail.tsx");
  "routes/exhibits/index": typeof import("./src/routes/exhibits/index.tsx");
  "routes/exhibits/detail": typeof import("./src/routes/exhibits/detail.tsx");
  "routes/research/index": typeof import("./src/routes/research/index.tsx");
  "routes/research/detail": typeof import("./src/routes/research/detail.tsx");
  "routes/citations/index": typeof import("./src/routes/citations/index.tsx");
  "routes/war-room/index": typeof import("./src/routes/war-room/index.tsx");
  "routes/war-room/detail": typeof import("./src/routes/war-room/detail.tsx");
  "routes/pleading/builder": typeof import("./src/routes/pleading/builder.tsx");
  "routes/drafting/index": typeof import("./src/routes/drafting/index.tsx");
  "routes/litigation/builder": typeof import("./src/routes/litigation/builder.tsx");
  "routes/billing/index": typeof import("./src/routes/billing/index.tsx");
  "routes/crm/index": typeof import("./src/routes/crm/index.tsx");
  "routes/crm/client-detail": typeof import("./src/routes/crm/client-detail.tsx");
  "routes/compliance/index": typeof import("./src/routes/compliance/index.tsx");
  "routes/practice/index": typeof import("./src/routes/practice/index.tsx");
  "routes/daf/index": typeof import("./src/routes/daf/index.tsx");
  "routes/entities/index": typeof import("./src/routes/entities/index.tsx");
  "routes/data-platform/index": typeof import("./src/routes/data-platform/index.tsx");
  "routes/analytics/index": typeof import("./src/routes/analytics/index.tsx");
  "routes/library/index": typeof import("./src/routes/library/index.tsx");
  "routes/clauses/index": typeof import("./src/routes/clauses/index.tsx");
  "routes/jurisdiction/index": typeof import("./src/routes/jurisdiction/index.tsx");
  "routes/rules/index": typeof import("./src/routes/rules/index.tsx");
  "routes/calendar/index": typeof import("./src/routes/calendar/index.tsx");
  "routes/messages/index": typeof import("./src/routes/messages/index.tsx");
  "routes/profile/index": typeof import("./src/routes/profile/index.tsx");
  "routes/admin/index": typeof import("./src/routes/admin/index.tsx");
  "routes/admin/theme-settings": typeof import("./src/routes/admin/theme-settings.tsx");
  "routes/real-estate/portfolio-summary": typeof import("./src/routes/real-estate/portfolio-summary.tsx");
  "routes/real-estate/inventory": typeof import("./src/routes/real-estate/inventory.tsx");
  "routes/real-estate/utilization": typeof import("./src/routes/real-estate/utilization.tsx");
  "routes/real-estate/outgrants": typeof import("./src/routes/real-estate/outgrants.tsx");
  "routes/real-estate/solicitations": typeof import("./src/routes/real-estate/solicitations.tsx");
  "routes/real-estate/relocation": typeof import("./src/routes/real-estate/relocation.tsx");
  "routes/real-estate/cost-share": typeof import("./src/routes/real-estate/cost-share.tsx");
  "routes/real-estate/disposal": typeof import("./src/routes/real-estate/disposal.tsx");
  "routes/real-estate/acquisition": typeof import("./src/routes/real-estate/acquisition.tsx");
  "routes/real-estate/encroachment": typeof import("./src/routes/real-estate/encroachment.tsx");
  "routes/real-estate/user-management": typeof import("./src/routes/real-estate/user-management.tsx");
  "routes/real-estate/audit-readiness": typeof import("./src/routes/real-estate/audit-readiness.tsx");
};