// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/cases": {
    params: {};
  };
  "/cases/create": {
    params: {};
  };
  "/cases/:caseId": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/overview": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/calendar": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/analytics": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/operations": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/insights": {
    params: {
      "caseId": string;
    };
  };
  "/cases/:caseId/financials": {
    params: {
      "caseId": string;
    };
  };
  "/docket": {
    params: {};
  };
  "/docket/:docketId": {
    params: {
      "docketId": string;
    };
  };
  "/documents": {
    params: {};
  };
  "/documents/upload": {
    params: {};
  };
  "/documents/:documentId": {
    params: {
      "documentId": string;
    };
  };
  "/correspondence": {
    params: {};
  };
  "/correspondence/compose": {
    params: {};
  };
  "/workflows": {
    params: {};
  };
  "/workflows/:workflowId": {
    params: {
      "workflowId": string;
    };
  };
  "/discovery": {
    params: {};
  };
  "/discovery/:discoveryId": {
    params: {
      "discoveryId": string;
    };
  };
  "/evidence": {
    params: {};
  };
  "/evidence/:evidenceId": {
    params: {
      "evidenceId": string;
    };
  };
  "/exhibits": {
    params: {};
  };
  "/exhibits/:exhibitId": {
    params: {
      "exhibitId": string;
    };
  };
  "/research": {
    params: {};
  };
  "/research/:researchId": {
    params: {
      "researchId": string;
    };
  };
  "/citations": {
    params: {};
  };
  "/war_room": {
    params: {};
  };
  "/war_room/:roomId": {
    params: {
      "roomId": string;
    };
  };
  "/pleadings": {
    params: {};
  };
  "/drafting": {
    params: {};
  };
  "/litigation": {
    params: {};
  };
  "/litigation_builder": {
    params: {};
  };
  "/billing": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/crm": {
    params: {};
  };
  "/crm/:clientId": {
    params: {
      "clientId": string;
    };
  };
  "/compliance": {
    params: {};
  };
  "/practice": {
    params: {};
  };
  "/daf": {
    params: {};
  };
  "/entities": {
    params: {};
  };
  "/data_platform": {
    params: {};
  };
  "/analytics": {
    params: {};
  };
  "/library": {
    params: {};
  };
  "/clauses": {
    params: {};
  };
  "/jurisdiction": {
    params: {};
  };
  "/rules_engine": {
    params: {};
  };
  "/calendar": {
    params: {};
  };
  "/messages": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/theme": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/theme-settings": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/roles": {
    params: {};
  };
  "/admin/permissions": {
    params: {};
  };
  "/admin/integrations": {
    params: {};
  };
  "/admin/backup": {
    params: {};
  };
  "/audit": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/forgot-password" | "/reset-password" | "/dashboard" | "/cases" | "/cases/create" | "/cases/:caseId" | "/cases/:caseId/overview" | "/cases/:caseId/calendar" | "/cases/:caseId/analytics" | "/cases/:caseId/operations" | "/cases/:caseId/insights" | "/cases/:caseId/financials" | "/docket" | "/docket/:docketId" | "/documents" | "/documents/upload" | "/documents/:documentId" | "/correspondence" | "/correspondence/compose" | "/workflows" | "/workflows/:workflowId" | "/discovery" | "/discovery/:discoveryId" | "/evidence" | "/evidence/:evidenceId" | "/exhibits" | "/exhibits/:exhibitId" | "/research" | "/research/:researchId" | "/citations" | "/war_room" | "/war_room/:roomId" | "/pleadings" | "/drafting" | "/litigation" | "/litigation_builder" | "/billing" | "/reports" | "/crm" | "/crm/:clientId" | "/compliance" | "/practice" | "/daf" | "/entities" | "/data_platform" | "/analytics" | "/library" | "/clauses" | "/jurisdiction" | "/rules_engine" | "/calendar" | "/messages" | "/profile" | "/settings" | "/settings/theme" | "/admin" | "/admin/settings" | "/admin/theme-settings" | "/admin/users" | "/admin/roles" | "/admin/permissions" | "/admin/integrations" | "/admin/backup" | "/audit" | "/*";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/dashboard" | "/cases" | "/cases/create" | "/cases/:caseId" | "/cases/:caseId/overview" | "/cases/:caseId/calendar" | "/cases/:caseId/analytics" | "/cases/:caseId/operations" | "/cases/:caseId/insights" | "/cases/:caseId/financials" | "/docket" | "/docket/:docketId" | "/documents" | "/documents/upload" | "/documents/:documentId" | "/correspondence" | "/correspondence/compose" | "/workflows" | "/workflows/:workflowId" | "/discovery" | "/discovery/:discoveryId" | "/evidence" | "/evidence/:evidenceId" | "/exhibits" | "/exhibits/:exhibitId" | "/research" | "/research/:researchId" | "/citations" | "/war_room" | "/war_room/:roomId" | "/pleadings" | "/drafting" | "/litigation" | "/litigation_builder" | "/billing" | "/reports" | "/crm" | "/crm/:clientId" | "/compliance" | "/practice" | "/daf" | "/entities" | "/data_platform" | "/analytics" | "/library" | "/clauses" | "/jurisdiction" | "/rules_engine" | "/calendar" | "/messages" | "/profile" | "/settings" | "/settings/theme" | "/admin" | "/admin/settings" | "/admin/theme-settings" | "/admin/users" | "/admin/roles" | "/admin/permissions" | "/admin/integrations" | "/admin/backup" | "/audit";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/cases/index.tsx": {
    id: "routes/cases/index";
    page: "/cases";
  };
  "routes/cases/create.tsx": {
    id: "routes/cases/create";
    page: "/cases/create";
  };
  "routes/cases/case-detail.tsx": {
    id: "routes/cases/case-detail";
    page: "/cases/:caseId";
  };
  "routes/cases/overview.tsx": {
    id: "routes/cases/overview";
    page: "/cases/:caseId/overview";
  };
  "routes/cases/calendar.tsx": {
    id: "routes/cases/calendar";
    page: "/cases/:caseId/calendar";
  };
  "routes/cases/analytics.tsx": {
    id: "routes/cases/analytics";
    page: "/cases/:caseId/analytics";
  };
  "routes/cases/operations.tsx": {
    id: "routes/cases/operations";
    page: "/cases/:caseId/operations";
  };
  "routes/cases/insights.tsx": {
    id: "routes/cases/insights";
    page: "/cases/:caseId/insights";
  };
  "routes/cases/financials.tsx": {
    id: "routes/cases/financials";
    page: "/cases/:caseId/financials";
  };
  "routes/docket/index.tsx": {
    id: "routes/docket/index";
    page: "/docket";
  };
  "routes/docket/detail.tsx": {
    id: "routes/docket/detail";
    page: "/docket/:docketId";
  };
  "routes/documents/index.tsx": {
    id: "routes/documents/index";
    page: "/documents";
  };
  "routes/documents/upload.tsx": {
    id: "routes/documents/upload";
    page: "/documents/upload";
  };
  "routes/documents/detail.tsx": {
    id: "routes/documents/detail";
    page: "/documents/:documentId";
  };
  "routes/correspondence/index.tsx": {
    id: "routes/correspondence/index";
    page: "/correspondence";
  };
  "routes/correspondence/compose.tsx": {
    id: "routes/correspondence/compose";
    page: "/correspondence/compose";
  };
  "routes/workflows/index.tsx": {
    id: "routes/workflows/index";
    page: "/workflows";
  };
  "routes/workflows/detail.tsx": {
    id: "routes/workflows/detail";
    page: "/workflows/:workflowId";
  };
  "routes/discovery/index.tsx": {
    id: "routes/discovery/index";
    page: "/discovery";
  };
  "routes/discovery/detail.tsx": {
    id: "routes/discovery/detail";
    page: "/discovery/:discoveryId";
  };
  "routes/evidence/index.tsx": {
    id: "routes/evidence/index";
    page: "/evidence";
  };
  "routes/evidence/detail.tsx": {
    id: "routes/evidence/detail";
    page: "/evidence/:evidenceId";
  };
  "routes/exhibits/index.tsx": {
    id: "routes/exhibits/index";
    page: "/exhibits";
  };
  "routes/exhibits/detail.tsx": {
    id: "routes/exhibits/detail";
    page: "/exhibits/:exhibitId";
  };
  "routes/research/index.tsx": {
    id: "routes/research/index";
    page: "/research";
  };
  "routes/research/detail.tsx": {
    id: "routes/research/detail";
    page: "/research/:researchId";
  };
  "routes/citations/index.tsx": {
    id: "routes/citations/index";
    page: "/citations";
  };
  "routes/war-room/index.tsx": {
    id: "routes/war-room/index";
    page: "/war_room";
  };
  "routes/war-room/detail.tsx": {
    id: "routes/war-room/detail";
    page: "/war_room/:roomId";
  };
  "routes/pleadings/index.tsx": {
    id: "routes/pleadings/index";
    page: "/pleadings";
  };
  "routes/drafting/index.tsx": {
    id: "routes/drafting/index";
    page: "/drafting";
  };
  "routes/litigation/index.tsx": {
    id: "routes/litigation/index";
    page: "/litigation";
  };
  "routes/litigation/builder.tsx": {
    id: "routes/litigation/builder";
    page: "/litigation_builder";
  };
  "routes/billing/index.tsx": {
    id: "routes/billing/index";
    page: "/billing";
  };
  "routes/reports/index.tsx": {
    id: "routes/reports/index";
    page: "/reports";
  };
  "routes/crm/index.tsx": {
    id: "routes/crm/index";
    page: "/crm";
  };
  "routes/crm/client-detail.tsx": {
    id: "routes/crm/client-detail";
    page: "/crm/:clientId";
  };
  "routes/compliance/index.tsx": {
    id: "routes/compliance/index";
    page: "/compliance";
  };
  "routes/practice/index.tsx": {
    id: "routes/practice/index";
    page: "/practice";
  };
  "routes/daf/index.tsx": {
    id: "routes/daf/index";
    page: "/daf";
  };
  "routes/entities/index.tsx": {
    id: "routes/entities/index";
    page: "/entities";
  };
  "routes/data-platform/index.tsx": {
    id: "routes/data-platform/index";
    page: "/data_platform";
  };
  "routes/analytics/index.tsx": {
    id: "routes/analytics/index";
    page: "/analytics";
  };
  "routes/library/index.tsx": {
    id: "routes/library/index";
    page: "/library";
  };
  "routes/clauses/index.tsx": {
    id: "routes/clauses/index";
    page: "/clauses";
  };
  "routes/jurisdiction/index.tsx": {
    id: "routes/jurisdiction/index";
    page: "/jurisdiction";
  };
  "routes/rules/index.tsx": {
    id: "routes/rules/index";
    page: "/rules_engine";
  };
  "routes/calendar/index.tsx": {
    id: "routes/calendar/index";
    page: "/calendar";
  };
  "routes/messages/index.tsx": {
    id: "routes/messages/index";
    page: "/messages";
  };
  "routes/profile/index.tsx": {
    id: "routes/profile/index";
    page: "/profile";
  };
  "routes/settings/index.tsx": {
    id: "routes/settings/index";
    page: "/settings";
  };
  "routes/settings/theme.tsx": {
    id: "routes/settings/theme";
    page: "/settings/theme";
  };
  "routes/admin/index.tsx": {
    id: "routes/admin/index";
    page: "/admin";
  };
  "routes/admin/settings.tsx": {
    id: "routes/admin/settings";
    page: "/admin/settings";
  };
  "routes/admin/theme-settings.tsx": {
    id: "routes/admin/theme-settings";
    page: "/admin/theme-settings";
  };
  "routes/admin/users.tsx": {
    id: "routes/admin/users";
    page: "/admin/users";
  };
  "routes/admin/roles.tsx": {
    id: "routes/admin/roles";
    page: "/admin/roles";
  };
  "routes/admin/permissions.tsx": {
    id: "routes/admin/permissions";
    page: "/admin/permissions";
  };
  "routes/admin/integrations.tsx": {
    id: "routes/admin/integrations";
    page: "/admin/integrations";
  };
  "routes/admin/backup.tsx": {
    id: "routes/admin/backup";
    page: "/admin/backup";
  };
  "routes/audit/index.tsx": {
    id: "routes/audit/index";
    page: "/audit";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/auth/login": typeof import("./src/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./src/routes/auth/register.tsx");
  "routes/auth/forgot-password": typeof import("./src/routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./src/routes/auth/reset-password.tsx");
  "routes/layout": typeof import("./src/routes/layout.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/dashboard/index": typeof import("./src/routes/dashboard/index.tsx");
  "routes/cases/index": typeof import("./src/routes/cases/index.tsx");
  "routes/cases/create": typeof import("./src/routes/cases/create.tsx");
  "routes/cases/case-detail": typeof import("./src/routes/cases/case-detail.tsx");
  "routes/cases/overview": typeof import("./src/routes/cases/overview.tsx");
  "routes/cases/calendar": typeof import("./src/routes/cases/calendar.tsx");
  "routes/cases/analytics": typeof import("./src/routes/cases/analytics.tsx");
  "routes/cases/operations": typeof import("./src/routes/cases/operations.tsx");
  "routes/cases/insights": typeof import("./src/routes/cases/insights.tsx");
  "routes/cases/financials": typeof import("./src/routes/cases/financials.tsx");
  "routes/docket/index": typeof import("./src/routes/docket/index.tsx");
  "routes/docket/detail": typeof import("./src/routes/docket/detail.tsx");
  "routes/documents/index": typeof import("./src/routes/documents/index.tsx");
  "routes/documents/upload": typeof import("./src/routes/documents/upload.tsx");
  "routes/documents/detail": typeof import("./src/routes/documents/detail.tsx");
  "routes/correspondence/index": typeof import("./src/routes/correspondence/index.tsx");
  "routes/correspondence/compose": typeof import("./src/routes/correspondence/compose.tsx");
  "routes/workflows/index": typeof import("./src/routes/workflows/index.tsx");
  "routes/workflows/detail": typeof import("./src/routes/workflows/detail.tsx");
  "routes/discovery/index": typeof import("./src/routes/discovery/index.tsx");
  "routes/discovery/detail": typeof import("./src/routes/discovery/detail.tsx");
  "routes/evidence/index": typeof import("./src/routes/evidence/index.tsx");
  "routes/evidence/detail": typeof import("./src/routes/evidence/detail.tsx");
  "routes/exhibits/index": typeof import("./src/routes/exhibits/index.tsx");
  "routes/exhibits/detail": typeof import("./src/routes/exhibits/detail.tsx");
  "routes/research/index": typeof import("./src/routes/research/index.tsx");
  "routes/research/detail": typeof import("./src/routes/research/detail.tsx");
  "routes/citations/index": typeof import("./src/routes/citations/index.tsx");
  "routes/war-room/index": typeof import("./src/routes/war-room/index.tsx");
  "routes/war-room/detail": typeof import("./src/routes/war-room/detail.tsx");
  "routes/pleadings/index": typeof import("./src/routes/pleadings/index.tsx");
  "routes/drafting/index": typeof import("./src/routes/drafting/index.tsx");
  "routes/litigation/index": typeof import("./src/routes/litigation/index.tsx");
  "routes/litigation/builder": typeof import("./src/routes/litigation/builder.tsx");
  "routes/billing/index": typeof import("./src/routes/billing/index.tsx");
  "routes/reports/index": typeof import("./src/routes/reports/index.tsx");
  "routes/crm/index": typeof import("./src/routes/crm/index.tsx");
  "routes/crm/client-detail": typeof import("./src/routes/crm/client-detail.tsx");
  "routes/compliance/index": typeof import("./src/routes/compliance/index.tsx");
  "routes/practice/index": typeof import("./src/routes/practice/index.tsx");
  "routes/daf/index": typeof import("./src/routes/daf/index.tsx");
  "routes/entities/index": typeof import("./src/routes/entities/index.tsx");
  "routes/data-platform/index": typeof import("./src/routes/data-platform/index.tsx");
  "routes/analytics/index": typeof import("./src/routes/analytics/index.tsx");
  "routes/library/index": typeof import("./src/routes/library/index.tsx");
  "routes/clauses/index": typeof import("./src/routes/clauses/index.tsx");
  "routes/jurisdiction/index": typeof import("./src/routes/jurisdiction/index.tsx");
  "routes/rules/index": typeof import("./src/routes/rules/index.tsx");
  "routes/calendar/index": typeof import("./src/routes/calendar/index.tsx");
  "routes/messages/index": typeof import("./src/routes/messages/index.tsx");
  "routes/profile/index": typeof import("./src/routes/profile/index.tsx");
  "routes/settings/index": typeof import("./src/routes/settings/index.tsx");
  "routes/settings/theme": typeof import("./src/routes/settings/theme.tsx");
  "routes/admin/index": typeof import("./src/routes/admin/index.tsx");
  "routes/admin/settings": typeof import("./src/routes/admin/settings.tsx");
  "routes/admin/theme-settings": typeof import("./src/routes/admin/theme-settings.tsx");
  "routes/admin/users": typeof import("./src/routes/admin/users.tsx");
  "routes/admin/roles": typeof import("./src/routes/admin/roles.tsx");
  "routes/admin/permissions": typeof import("./src/routes/admin/permissions.tsx");
  "routes/admin/integrations": typeof import("./src/routes/admin/integrations.tsx");
  "routes/admin/backup": typeof import("./src/routes/admin/backup.tsx");
  "routes/audit/index": typeof import("./src/routes/audit/index.tsx");
  "routes/404": typeof import("./src/routes/404.tsx");
};