import { Role } from '@common/enums/role.enum';
import { Permission } from '@common/enums/permission.enum';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.SUPER_ADMIN]: [
    Permission.CASE_CREATE,
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.CASE_DELETE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.DOCUMENT_DELETE,
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
    Permission.BILLING_DELETE,
    Permission.USER_MANAGE,
    Permission.SYSTEM_ADMIN,
  ],
  [Role.SENIOR_PARTNER]: [
    Permission.CASE_CREATE,
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.CASE_DELETE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.DOCUMENT_DELETE,
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
    Permission.BILLING_DELETE,
    Permission.USER_MANAGE,
  ],
  [Role.PARTNER]: [
    Permission.CASE_CREATE,
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
  ],
  [Role.ASSOCIATE]: [
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_READ,
  ],
  [Role.PARALEGAL]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
  ],
  [Role.LEGAL_SECRETARY]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
  ],
  [Role.ADMINISTRATOR]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
    Permission.BILLING_READ,
    Permission.USER_MANAGE,
  ],
  [Role.CLIENT_USER]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
  ],
  [Role.GUEST]: [
    Permission.CASE_READ,
  ],
};
