import { UserRole } from '@common/enums/role.enum';
import { Permission } from '@common/enums/permission.enum';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: [
    Permission.CASE_CREATE,
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.CASE_DELETE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.DOCUMENT_DELETE,
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
    Permission.BILLING_DELETE,
    Permission.USER_MANAGE,
    Permission.SYSTEM_ADMIN,
  ],
  [UserRole.ADMIN]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
    Permission.BILLING_READ,
    Permission.USER_MANAGE,
  ],
  [UserRole.PARTNER]: [
    Permission.CASE_CREATE,
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
  ],
  [UserRole.SENIOR_ASSOCIATE]: [
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_READ,
  ],
  [UserRole.ASSOCIATE]: [
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_READ,
  ],
  [UserRole.JUNIOR_ASSOCIATE]: [
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_READ,
  ],
  [UserRole.ATTORNEY]: [
    Permission.CASE_READ,
    Permission.CASE_UPDATE,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
    Permission.BILLING_READ,
  ],
  [UserRole.PARALEGAL]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
    Permission.DOCUMENT_UPDATE,
  ],
  [UserRole.LEGAL_ASSISTANT]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
  ],
  [UserRole.CLERK]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_CREATE,
    Permission.DOCUMENT_READ,
  ],
  [UserRole.INTERN]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
  ],
  [UserRole.ACCOUNTANT]: [
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
    Permission.BILLING_DELETE,
  ],
  [UserRole.BILLING_SPECIALIST]: [
    Permission.BILLING_CREATE,
    Permission.BILLING_READ,
    Permission.BILLING_UPDATE,
  ],
  [UserRole.IT_ADMIN]: [
    Permission.USER_MANAGE,
    Permission.SYSTEM_ADMIN,
  ],
  [UserRole.STAFF]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
  ],
  [UserRole.USER]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
  ],
  [UserRole.CLIENT]: [
    Permission.CASE_READ,
    Permission.DOCUMENT_READ,
  ],
};
