/** * @module components/common/DocketSkeleton * @category Loading States * @description Skeleton screens for docket table and calendar loading states */

import React from 'react';

import { useTheme } from "@/hooks/useTheme";
import { cn } from '@/lib/cn';
// ============================================================================
// DOCKET TABLE SKELETON
// ============================================================================
export const DocketTableSkeleton: React.FC<{ rows?: number }> = ({ rows = 10 }) => {
  const { theme } = useTheme(); return (<div className="flex flex-col h-full"> {/* Header */} <div className={cn("hidden md:flex items-center px-6 py-3 border-b shrink-0", theme.surface.highlight, theme.border.default)}> <div className="w-20 h-3 bg-slate-200 rounded animate-pulse shrink-0" /> <div className="w-24 h-3 bg-slate-200 rounded animate-pulse shrink-0 ml-6" /> <div className="w-32 h-3 bg-slate-200 rounded animate-pulse shrink-0 ml-6" /> <div className="flex-1 h-3 bg-slate-200 rounded animate-pulse ml-6" /> <div className="w-16 h-3 bg-slate-200 rounded animate-pulse shrink-0 ml-6" /> <div className="w-32 h-3 bg-slate-200 rounded animate-pulse shrink-0 ml-6" /> </div> {/* Rows - IDENTITY-STABLE KEYS */} <div className="flex-1 overflow-hidden"> {Array.from({ length: rows }).map((_, i) => (<div key={`docket-row-${i}`} className={cn("hidden md:flex items-center px-6 border-b h-[72px]", theme.border.default)} > {/* Sequence */} <div className="w-20 shrink-0"> <div className="w-12 h-4 bg-slate-200 rounded animate-pulse" /> </div> {/* Date */} <div className="w-24 shrink-0"> <div className="w-20 h-3 bg-slate-200 rounded animate-pulse" /> </div> {/* Case Ref */} <div className="w-32 shrink-0 px-2"> <div className="w-28 h-3 bg-slate-200 rounded animate-pulse" /> </div> {/* Content */} <div className="flex-1 px-4 space-y-2"> <div className="w-3/4 h-4 bg-slate-200 rounded animate-pulse" /> <div className="w-1/2 h-3 bg-slate-200 rounded animate-pulse" /> </div> {/* Doc Icon */} <div className="w-16 shrink-0 flex justify-center"> <div className="w-8 h-8 bg-slate-200 rounded animate-pulse" /> </div> {/* Status */} <div className="w-32 shrink-0 flex justify-end"> <div className="w-20 h-6 bg-slate-200 rounded-full animate-pulse" /> </div> </div>))} {/* Mobile View - IDENTITY-STABLE KEYS */} <div className="md:hidden space-y-3 p-4"> {Array.from({ length: rows }).map((_, i) => (<div key={`docket-mobile-${i}`} className={cn("p-4 rounded-lg border h-[140px]", theme.border.default, theme.surface.default)} > <div className="flex justify-between items-start mb-3"> <div className="flex gap-2"> <div className="w-10 h-4 bg-slate-200 rounded animate-pulse" /> <div className="w-16 h-4 bg-slate-200 rounded animate-pulse" /> </div> <div className="w-12 h-5 bg-slate-200 rounded animate-pulse" /> </div> <div className="space-y-2"> <div className="w-full h-4 bg-slate-200 rounded animate-pulse" /> <div className="w-3/4 h-3 bg-slate-200 rounded animate-pulse" /> </div> <div className="flex justify-between items-center mt-4 pt-3 border-t border-slate-100"> <div className="w-20 h-3 bg-slate-200 rounded animate-pulse" /> <div className="w-16 h-3 bg-slate-200 rounded animate-pulse" /> </div> </div>))} </div> </div> </div>);
}; // ============================================================================
// DOCKET CALENDAR SKELETON
// ============================================================================
export const DocketCalendarSkeleton: React.FC = () => {
  const { theme } = useTheme(); return (<div className={cn("flex flex-col h-full rounded-lg border shadow-sm overflow-hidden", theme.surface.default, theme.border.default)}> {/* Header */} <div className={cn("p-4 border-b flex justify-between items-center", theme.surface.highlight, theme.border.default)}> <div className="flex items-center gap-4"> <div className="w-12 h-12 bg-slate-200 rounded-lg animate-pulse" /> <div> <div className="w-32 h-5 bg-slate-200 rounded animate-pulse mb-2" /> <div className="w-48 h-3 bg-slate-200 rounded animate-pulse" /> </div> </div> <div className="flex gap-1"> <div className="w-8 h-8 bg-slate-200 rounded animate-pulse" /> <div className="w-16 h-8 bg-slate-200 rounded animate-pulse" /> <div className="w-8 h-8 bg-slate-200 rounded animate-pulse" /> </div> </div> {/* Calendar Grid */} <div className={cn("flex-1 p-px grid grid-cols-7 gap-px overflow-y-auto", theme.surface.highlight)}> {/* Day Headers */} {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day, _i) => (<div key={day} className={cn("p-2 text-center border-b", theme.surface.highlight, theme.border.default)}> <div className="w-8 h-3 bg-slate-200 rounded animate-pulse mx-auto" /> </div>))} {/* Calendar Days - DETERMINISTIC RENDERING: Use stable pattern instead of Math.random */} {Array.from({ length: 35 }).map((_, i) => (<div key={`calendar-day-${i}`} className={cn("p-2 min-h-[120px] flex flex-col", theme.surface.default)} > <div className="w-6 h-6 bg-slate-200 rounded-full animate-pulse mb-2" /> {/* DETERMINISTIC: Show deadlines for specific days (e.g., every 3rd and 5th day) */} {(i % 3 === 0 || i % 5 === 0) && (<div className="space-y-1"> <div className="w-full h-4 bg-slate-200 rounded animate-pulse" /> {i % 2 === 0 && (<div className="w-3/4 h-4 bg-slate-200 rounded animate-pulse" />)} </div>)} </div>))} </div> </div>);
}; // ============================================================================
// DOCKET STATS SKELETON
// ============================================================================
export const DocketStatsSkeleton: React.FC = () => {
  const { theme } = useTheme(); return (<div className="grid grid-cols-1 md:grid-cols-4 gap-4"> {Array.from({ length: 4 }).map((_, i) => (<div key={i} className={cn("p-6 rounded-lg border shadow-sm", theme.surface.default, theme.border.default)} > <div className="w-24 h-3 bg-slate-200 rounded animate-pulse mb-3" /> <div className="w-16 h-8 bg-slate-200 rounded animate-pulse mb-2" /> <div className="w-32 h-3 bg-slate-200 rounded animate-pulse" /> </div>))} </div>);
}; // ============================================================================
// DOCKET FILTER PANEL SKELETON
// ============================================================================
export const DocketFilterSkeleton: React.FC = () => {
  const { theme } = useTheme(); return (<div className={cn("w-full md:w-64 rounded-lg border shadow-sm flex flex-col shrink-0", theme.surface.default, theme.border.default)}> <div className={cn("p-4 border-b", theme.border.default)}> <div className="w-24 h-4 bg-slate-200 rounded animate-pulse" /> </div> <div className="p-4 space-y-4"> {/* Search */} <div className="w-full h-10 bg-slate-200 rounded animate-pulse" /> {/* Filter Options */} <div> <div className="w-16 h-3 bg-slate-200 rounded animate-pulse mb-2" /> <div className="space-y-2"> {Array.from({ length: 3 }).map((_, i) => (<div key={i} className="w-full h-9 bg-slate-200 rounded animate-pulse" />))} </div> </div> {/* Cases */} <div> <div className="w-20 h-3 bg-slate-200 rounded animate-pulse mb-2" /> <div className="space-y-2"> {Array.from({ length: 5 }).map((_, i) => (<div key={i} className="space-y-1"> <div className="w-full h-4 bg-slate-200 rounded animate-pulse" /> <div className="w-3/4 h-3 bg-slate-200 rounded animate-pulse" /> </div>))} </div> </div> </div> </div>);
}; // Default export for backward compatibility
export default DocketTableSkeleton;
