/**
 * Export Types and Interfaces
 * @module lib/export/types
 *
 * Comprehensive type definitions for report export functionality.
 * Supports PDF, Excel (XLSX), and CSV export formats with templates
 * for billing, trust accounts, and time entry reports.
 */

// =============================================================================
// Core Export Types
// =============================================================================

/**
 * Supported export format types
 */
export type ExportFormat = 'pdf' | 'excel' | 'csv';

/**
 * Report types available for export
 */
export type ReportType =
  | 'billing'
  | 'trust'
  | 'time-entries'
  | 'invoices'
  | 'expenses'
  | 'clients'
  | 'reconciliation'
  | 'compliance'
  | 'custom';

/**
 * MIME types for export formats
 */
export const MIME_TYPES: Readonly<Record<ExportFormat, string>> = {
  pdf: 'application/pdf',
  excel: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  csv: 'text/csv',
} as const;

/**
 * File extensions for export formats
 */
export const FILE_EXTENSIONS: Readonly<Record<ExportFormat, string>> = {
  pdf: '.pdf',
  excel: '.xlsx',
  csv: '.csv',
} as const;

// =============================================================================
// Column Definition Types
// =============================================================================

/**
 * Column alignment options
 */
export type ColumnAlignment = 'left' | 'center' | 'right';

/**
 * Data type for formatting purposes
 */
export type ColumnDataType =
  | 'string'
  | 'number'
  | 'currency'
  | 'date'
  | 'datetime'
  | 'boolean'
  | 'percentage';

/**
 * Column definition for export tables
 * Defines how data should be extracted and formatted
 */
export interface ExportColumn<T = unknown> {
  /** Column header text */
  readonly header: string;
  /** Property key or accessor function to extract value from data row */
  readonly accessor: keyof T | ((row: T) => unknown);
  /** Data type for formatting */
  readonly dataType?: ColumnDataType;
  /** Column width (for Excel/PDF) */
  readonly width?: number;
  /** Text alignment */
  readonly align?: ColumnAlignment;
  /** Custom formatter function */
  readonly formatter?: (value: unknown, row: T) => string;
  /** Whether to include in totals row (for numeric columns) */
  readonly includeInTotals?: boolean;
  /** Whether column is hidden (useful for conditional columns) */
  readonly hidden?: boolean;
}

// =============================================================================
// Base Export Options
// =============================================================================

/**
 * Base options shared across all export formats
 */
export interface BaseExportOptions<T = unknown> {
  /** Report title */
  readonly title: string;
  /** Report subtitle or description */
  readonly subtitle?: string;
  /** Column definitions */
  readonly columns: readonly ExportColumn<T>[];
  /** Data rows to export */
  readonly data: readonly T[];
  /** Custom filename (without extension) */
  readonly filename?: string;
  /** Report type for template selection */
  readonly reportType?: ReportType;
  /** Date range for the report */
  readonly dateRange?: DateRange;
  /** Include generated timestamp */
  readonly includeTimestamp?: boolean;
  /** Include page numbers (PDF only) */
  readonly includePageNumbers?: boolean;
  /** Company/Firm information for headers */
  readonly firmInfo?: FirmInfo;
  /** Additional metadata for the report */
  readonly metadata?: ExportMetadata;
}

/**
 * Date range specification
 */
export interface DateRange {
  readonly start: Date | string;
  readonly end: Date | string;
}

/**
 * Firm/Company information for report headers
 */
export interface FirmInfo {
  readonly name: string;
  readonly address?: string;
  readonly phone?: string;
  readonly email?: string;
  readonly logo?: string; // Base64 or URL
  readonly website?: string;
}

/**
 * Additional metadata for reports
 */
export interface ExportMetadata {
  /** Generated by user/system */
  readonly generatedBy?: string;
  /** Generation timestamp */
  readonly generatedAt?: Date | string;
  /** Report version */
  readonly version?: string;
  /** Additional custom fields */
  readonly [key: string]: unknown;
}

// =============================================================================
// PDF-Specific Options
// =============================================================================

/**
 * Page orientation for PDF
 */
export type PageOrientation = 'portrait' | 'landscape';

/**
 * Page size presets
 */
export type PageSize = 'A4' | 'Letter' | 'Legal' | 'A3';

/**
 * PDF styling options
 */
export interface PDFStyling {
  /** Primary color for headers/accents */
  readonly primaryColor?: string;
  /** Secondary color for alternating rows */
  readonly secondaryColor?: string;
  /** Font family */
  readonly fontFamily?: string;
  /** Base font size in points */
  readonly fontSize?: number;
  /** Header font size in points */
  readonly headerFontSize?: number;
  /** Title font size in points */
  readonly titleFontSize?: number;
  /** Line height multiplier */
  readonly lineHeight?: number;
  /** Cell padding in points */
  readonly cellPadding?: number;
  /** Border color */
  readonly borderColor?: string;
  /** Border width */
  readonly borderWidth?: number;
}

/**
 * PDF page margins
 */
export interface PDFMargins {
  readonly top: number;
  readonly right: number;
  readonly bottom: number;
  readonly left: number;
}

/**
 * PDF-specific export options
 */
export interface PDFExportOptions<T = unknown> extends BaseExportOptions<T> {
  /** Page orientation */
  readonly orientation?: PageOrientation;
  /** Page size */
  readonly pageSize?: PageSize;
  /** Page margins in points */
  readonly margins?: PDFMargins;
  /** PDF styling options */
  readonly styling?: PDFStyling;
  /** Include cover page */
  readonly includeCoverPage?: boolean;
  /** Include summary section */
  readonly includeSummary?: boolean;
  /** Summary data for report */
  readonly summaryData?: ReportSummary;
  /** Header content for each page */
  readonly pageHeader?: string;
  /** Footer content for each page */
  readonly pageFooter?: string;
  /** Watermark text */
  readonly watermark?: string;
}

/**
 * Report summary data
 */
export interface ReportSummary {
  /** Summary label-value pairs */
  readonly items: readonly SummaryItem[];
  /** Summary title */
  readonly title?: string;
}

/**
 * Individual summary item
 */
export interface SummaryItem {
  readonly label: string;
  readonly value: string | number;
  readonly dataType?: ColumnDataType;
}

// =============================================================================
// Excel-Specific Options
// =============================================================================

/**
 * Excel sheet definition
 */
export interface ExcelSheet<T = unknown> {
  /** Sheet name (max 31 characters) */
  readonly name: string;
  /** Column definitions for this sheet */
  readonly columns: readonly ExportColumn<T>[];
  /** Data rows for this sheet */
  readonly data: readonly T[];
  /** Include auto-filter */
  readonly autoFilter?: boolean;
  /** Freeze header row */
  readonly freezeHeader?: boolean;
  /** Include totals row */
  readonly includeTotals?: boolean;
}

/**
 * Excel styling options
 */
export interface ExcelStyling {
  /** Header background color (hex) */
  readonly headerBgColor?: string;
  /** Header text color (hex) */
  readonly headerTextColor?: string;
  /** Alternating row color (hex) */
  readonly alternateRowColor?: string;
  /** Bold headers */
  readonly boldHeaders?: boolean;
  /** Auto-fit column widths */
  readonly autoFitColumns?: boolean;
  /** Default row height */
  readonly rowHeight?: number;
  /** Default column width */
  readonly defaultColumnWidth?: number;
}

/**
 * Excel-specific export options
 */
export interface ExcelExportOptions<T = unknown> extends BaseExportOptions<T> {
  /** Multiple sheets (overrides single data/columns) */
  readonly sheets?: readonly ExcelSheet<T>[];
  /** Excel styling options */
  readonly styling?: ExcelStyling;
  /** Include auto-filter on main sheet */
  readonly autoFilter?: boolean;
  /** Freeze header row */
  readonly freezeHeader?: boolean;
  /** Include totals row */
  readonly includeTotals?: boolean;
  /** Include formulas for calculations */
  readonly includeFormulas?: boolean;
  /** Protected sheet (read-only) */
  readonly protectSheet?: boolean;
  /** Sheet protection password */
  readonly protectionPassword?: string;
}

// =============================================================================
// CSV-Specific Options
// =============================================================================

/**
 * CSV delimiter options
 */
export type CSVDelimiter = ',' | ';' | '\t' | '|';

/**
 * CSV line ending options
 */
export type CSVLineEnding = '\n' | '\r\n';

/**
 * CSV encoding options
 */
export type CSVEncoding = 'utf-8' | 'utf-8-bom' | 'utf-16';

/**
 * CSV-specific export options
 */
export interface CSVExportOptions<T = unknown> extends BaseExportOptions<T> {
  /** Field delimiter */
  readonly delimiter?: CSVDelimiter;
  /** Line ending style */
  readonly lineEnding?: CSVLineEnding;
  /** Include BOM for Excel compatibility */
  readonly includeBOM?: boolean;
  /** Character encoding */
  readonly encoding?: CSVEncoding;
  /** Quote all fields (not just those with special characters) */
  readonly quoteAll?: boolean;
  /** Quote character */
  readonly quoteChar?: '"' | "'";
  /** Escape character for quotes */
  readonly escapeChar?: '"' | '\\';
  /** Include header row */
  readonly includeHeaders?: boolean;
  /** Null value representation */
  readonly nullValue?: string;
}

// =============================================================================
// Export Result Types
// =============================================================================

/**
 * Export result containing the generated file
 */
export interface ExportResult {
  /** Generated file as Blob */
  readonly blob: Blob;
  /** Suggested filename with extension */
  readonly filename: string;
  /** MIME type of the file */
  readonly mimeType: string;
  /** File size in bytes */
  readonly size: number;
  /** Generation timestamp */
  readonly generatedAt: Date;
  /** Export format used */
  readonly format: ExportFormat;
  /** Row count exported */
  readonly rowCount: number;
}

/**
 * Export progress callback
 */
export type ExportProgressCallback = (progress: ExportProgress) => void;

/**
 * Export progress information
 */
export interface ExportProgress {
  /** Current phase */
  readonly phase: 'preparing' | 'generating' | 'formatting' | 'complete';
  /** Progress percentage (0-100) */
  readonly percentage: number;
  /** Current row being processed */
  readonly currentRow?: number;
  /** Total rows to process */
  readonly totalRows?: number;
  /** Status message */
  readonly message?: string;
}

// =============================================================================
// Report Template Types
// =============================================================================

/**
 * Pre-configured report template
 */
export interface ReportTemplate<T = unknown> {
  /** Template identifier */
  readonly id: string;
  /** Template display name */
  readonly name: string;
  /** Template description */
  readonly description?: string;
  /** Report type this template is for */
  readonly reportType: ReportType;
  /** Supported export formats */
  readonly supportedFormats: readonly ExportFormat[];
  /** Default column configuration */
  readonly columns: readonly ExportColumn<T>[];
  /** Default PDF options */
  readonly pdfDefaults?: Partial<PDFExportOptions<T>>;
  /** Default Excel options */
  readonly excelDefaults?: Partial<ExcelExportOptions<T>>;
  /** Default CSV options */
  readonly csvDefaults?: Partial<CSVExportOptions<T>>;
}

// =============================================================================
// Billing Report Types
// =============================================================================

/**
 * Billing report row data structure
 */
export interface BillingReportRow {
  readonly invoiceNumber: string;
  readonly clientName: string;
  readonly matterDescription: string;
  readonly invoiceDate: string;
  readonly dueDate: string;
  readonly amount: number;
  readonly paidAmount: number;
  readonly balanceDue: number;
  readonly status: string;
  readonly timeCharges: number;
  readonly expenseCharges: number;
}

/**
 * Trust account report row data structure
 */
export interface TrustReportRow {
  readonly accountNumber: string;
  readonly accountName: string;
  readonly clientName: string;
  readonly accountType: string;
  readonly balance: number;
  readonly lastReconciled: string;
  readonly status: string;
  readonly jurisdiction: string;
}

/**
 * Time entry report row data structure
 */
export interface TimeEntryReportRow {
  readonly date: string;
  readonly timekeeper: string;
  readonly clientName: string;
  readonly matterDescription: string;
  readonly activity: string;
  readonly description: string;
  readonly duration: number;
  readonly rate: number;
  readonly total: number;
  readonly status: string;
  readonly billable: boolean;
}

/**
 * Trust transaction report row data structure
 */
export interface TrustTransactionReportRow {
  readonly transactionDate: string;
  readonly transactionType: string;
  readonly description: string;
  readonly clientName: string;
  readonly amount: number;
  readonly balanceAfter: number;
  readonly checkNumber: string;
  readonly status: string;
  readonly payee: string;
  readonly payor: string;
}

/**
 * Expense report row data structure
 */
export interface ExpenseReportRow {
  readonly date: string;
  readonly category: string;
  readonly description: string;
  readonly vendor: string;
  readonly amount: number;
  readonly status: string;
  readonly clientName?: string;
  readonly matterDescription?: string;
  readonly billable: boolean;
}

// =============================================================================
// Export Service Configuration
// =============================================================================

/**
 * Global export service configuration
 */
export interface ExportServiceConfig {
  /** Default firm information */
  readonly defaultFirmInfo?: FirmInfo;
  /** Default PDF styling */
  readonly defaultPDFStyling?: PDFStyling;
  /** Default Excel styling */
  readonly defaultExcelStyling?: ExcelStyling;
  /** Default date format */
  readonly dateFormat?: string;
  /** Default datetime format */
  readonly datetimeFormat?: string;
  /** Default currency code */
  readonly currencyCode?: string;
  /** Default currency locale */
  readonly currencyLocale?: string;
  /** Maximum rows per export */
  readonly maxRows?: number;
  /** Enable compression for large exports */
  readonly enableCompression?: boolean;
}

/**
 * Default export service configuration
 */
export const DEFAULT_EXPORT_CONFIG: ExportServiceConfig = {
  dateFormat: 'MM/dd/yyyy',
  datetimeFormat: 'MM/dd/yyyy HH:mm',
  currencyCode: 'USD',
  currencyLocale: 'en-US',
  maxRows: 10000,
  enableCompression: true,
  defaultPDFStyling: {
    primaryColor: '#1e3a5f',
    secondaryColor: '#f8f9fa',
    fontFamily: 'Helvetica',
    fontSize: 10,
    headerFontSize: 12,
    titleFontSize: 18,
    lineHeight: 1.4,
    cellPadding: 8,
    borderColor: '#dee2e6',
    borderWidth: 0.5,
  },
  defaultExcelStyling: {
    headerBgColor: '1e3a5f',
    headerTextColor: 'ffffff',
    alternateRowColor: 'f8f9fa',
    boldHeaders: true,
    autoFitColumns: true,
    rowHeight: 20,
    defaultColumnWidth: 15,
  },
} as const;

// =============================================================================
// Type Guards
// =============================================================================

/**
 * Type guard for ExportFormat
 */
export function isExportFormat(value: unknown): value is ExportFormat {
  return value === 'pdf' || value === 'excel' || value === 'csv';
}

/**
 * Type guard for ReportType
 */
export function isReportType(value: unknown): value is ReportType {
  const validTypes: ReportType[] = [
    'billing',
    'trust',
    'time-entries',
    'invoices',
    'expenses',
    'clients',
    'reconciliation',
    'compliance',
    'custom',
  ];
  return typeof value === 'string' && validTypes.includes(value as ReportType);
}

// =============================================================================
// Utility Types
// =============================================================================

/**
 * Extract value type from ExportColumn accessor
 */
export type AccessorValue<T, C extends ExportColumn<T>> = C['accessor'] extends keyof T
  ? T[C['accessor']]
  : C['accessor'] extends (row: T) => infer R
    ? R
    : unknown;

/**
 * Options for any export format (union type)
 */
export type AnyExportOptions<T = unknown> =
  | PDFExportOptions<T>
  | ExcelExportOptions<T>
  | CSVExportOptions<T>;

/**
 * Format-specific options mapping
 */
export interface FormatOptionsMap<T = unknown> {
  readonly pdf: PDFExportOptions<T>;
  readonly excel: ExcelExportOptions<T>;
  readonly csv: CSVExportOptions<T>;
}

/**
 * Get options type for a specific format
 */
export type OptionsForFormat<F extends ExportFormat, T = unknown> = FormatOptionsMap<T>[F];
