import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTasksTable1765994418739 implements MigrationInterface {
    name = 'AddTasksTable1765994418739'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('To Do', 'In Progress', 'Blocked', 'Completed', 'Cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('Low', 'Medium', 'High', 'Critical')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'To Do', "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'Medium', "dueDate" TIMESTAMP, "caseId" character varying, "assignedTo" character varying, "parentTaskId" character varying, "tags" text, "estimatedHours" numeric(10,2), "actualHours" numeric(10,2) NOT NULL DEFAULT '0', "completionPercentage" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5534ba11e10f1a9953cbdaabf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_167a8092c79b7a2bc2cc18249e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8149db08955d2790ba626d74b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_559333e87dd4e0f4df6dda4453"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoice_number" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "case_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "client_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "clientName" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "matterDescription" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceDate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "dueDate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."invoices_status_enum" RENAME TO "invoices_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('Draft', 'draft', 'Sent', 'sent', 'Viewed', 'viewed', 'Partial', 'partial', 'Paid', 'paid', 'Overdue', 'overdue', 'Written Off', 'cancelled', 'refunded')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum" USING "status"::"text"::"public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'Draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "clientNumber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "clientType" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "evidenceNumber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "evidenceType" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "collectionDate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."cases_status_enum" RENAME TO "cases_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."cases_status_enum" AS ENUM('Open', 'open', 'Active', 'pending', 'Discovery', 'Trial', 'Settled', 'Closed', 'closed', 'Archived', 'archived', 'On Hold', 'on_hold')`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "status" TYPE "public"."cases_status_enum" USING "status"::"text"::"public"."cases_status_enum"`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "status" SET DEFAULT 'Open'`);
        await queryRunner.query(`DROP TYPE "public"."cases_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b33d2f7170600d7250ea875203"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177f4415839baae541187a672d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce0421e9bbc3b052184caf44c"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "case_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "duration" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "total" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."time_entries_status_enum" RENAME TO "time_entries_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."time_entries_status_enum" AS ENUM('Draft', 'draft', 'Submitted', 'submitted', 'Approved', 'approved', 'Billed', 'invoiced', 'Written Off', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "status" TYPE "public"."time_entries_status_enum" USING "status"::"text"::"public"."time_entries_status_enum"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "status" SET DEFAULT 'Draft'`);
        await queryRunner.query(`DROP TYPE "public"."time_entries_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "case_phases" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "case_phases" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."motions_type_enum" RENAME TO "motions_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."motions_type_enum" AS ENUM('Motion to Dismiss', 'motion_to_dismiss', 'Motion for Summary Judgment', 'motion_for_summary_judgment', 'Motion to Compel', 'motion_to_compel', 'Motion for Protective Order', 'motion_for_protective_order', 'Motion in Limine', 'motion_in_limine', 'Motion for Continuance', 'motion_for_continuance', 'Motion to Amend', 'motion_to_amend', 'Motion for Sanctions', 'Motion for Default Judgment', 'Motion to Strike', 'Motion for Reconsideration', 'motion_for_extension', 'emergency_motion', 'Other', 'other')`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "type" TYPE "public"."motions_type_enum" USING "type"::"text"::"public"."motions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."motions_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."motions_status_enum" RENAME TO "motions_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."motions_status_enum" AS ENUM('Draft', 'draft', 'Filed', 'filed', 'Pending', 'pending', 'Granted', 'granted', 'Denied', 'denied', 'Partially Granted', 'partially_granted', 'Withdrawn', 'withdrawn', 'Moot')`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "status" TYPE "public"."motions_status_enum" USING "status"::"text"::"public"."motions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "status" SET DEFAULT 'Draft'`);
        await queryRunner.query(`DROP TYPE "public"."motions_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "sequenceNumber" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "dateFiled" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "entryDate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."docket_entries_type_enum" RENAME TO "docket_entries_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."docket_entries_type_enum" AS ENUM('Filing', 'filing', 'Order', 'order', 'Notice', 'notice', 'Motion', 'motion', 'Hearing', 'hearing', 'Judgment', 'judgment', 'Minute Entry', 'minute_entry', 'Transcript', 'Exhibit', 'Correspondence', 'correspondence', 'pleading', 'discovery', 'Other', 'other')`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "type" TYPE "public"."docket_entries_type_enum" USING "type"::"text"::"public"."docket_entries_type_enum"`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "type" SET DEFAULT 'Filing'`);
        await queryRunner.query(`DROP TYPE "public"."docket_entries_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."depositions_status_enum" RENAME TO "depositions_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."depositions_status_enum" AS ENUM('SCHEDULED', 'scheduled', 'confirmed', 'IN_PROGRESS', 'in_progress', 'COMPLETED', 'completed', 'CANCELLED', 'cancelled', 'POSTPONED', 'postponed', 'TRANSCRIPTION_PENDING', 'TRANSCRIPTION_COMPLETE')`);
        await queryRunner.query(`ALTER TABLE "depositions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "depositions" ALTER COLUMN "status" TYPE "public"."depositions_status_enum" USING "status"::"text"::"public"."depositions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "depositions" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`DROP TYPE "public"."depositions_status_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_559333e87dd4e0f4df6dda4453" ON "invoices" ("status", "dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_8149db08955d2790ba626d74b6" ON "invoices" ("client_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_167a8092c79b7a2bc2cc18249e" ON "invoices" ("case_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ce0421e9bbc3b052184caf44c" ON "time_entries" ("status", "billable") `);
        await queryRunner.query(`CREATE INDEX "IDX_177f4415839baae541187a672d" ON "time_entries" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b33d2f7170600d7250ea875203" ON "time_entries" ("case_id", "date") `);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5534ba11e10f1a9953cbdaabf16" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5534ba11e10f1a9953cbdaabf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b33d2f7170600d7250ea875203"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177f4415839baae541187a672d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce0421e9bbc3b052184caf44c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_167a8092c79b7a2bc2cc18249e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8149db08955d2790ba626d74b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_559333e87dd4e0f4df6dda4453"`);
        await queryRunner.query(`CREATE TYPE "public"."depositions_status_enum_old" AS ENUM('CANCELLED', 'COMPLETED', 'IN_PROGRESS', 'POSTPONED', 'SCHEDULED', 'TRANSCRIPTION_COMPLETE', 'TRANSCRIPTION_PENDING')`);
        await queryRunner.query(`ALTER TABLE "depositions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "depositions" ALTER COLUMN "status" TYPE "public"."depositions_status_enum_old" USING "status"::"text"::"public"."depositions_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "depositions" ALTER COLUMN "status" SET DEFAULT 'SCHEDULED'`);
        await queryRunner.query(`DROP TYPE "public"."depositions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."depositions_status_enum_old" RENAME TO "depositions_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."docket_entries_type_enum_old" AS ENUM('Correspondence', 'Exhibit', 'Filing', 'Hearing', 'Judgment', 'Minute Entry', 'Motion', 'Notice', 'Order', 'Other', 'Transcript')`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "type" TYPE "public"."docket_entries_type_enum_old" USING "type"::"text"::"public"."docket_entries_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "type" SET DEFAULT 'Filing'`);
        await queryRunner.query(`DROP TYPE "public"."docket_entries_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."docket_entries_type_enum_old" RENAME TO "docket_entries_type_enum"`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "entryDate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "dateFiled" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "docket_entries" ALTER COLUMN "sequenceNumber" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."motions_status_enum_old" AS ENUM('Denied', 'Draft', 'Filed', 'Granted', 'Moot', 'Partially Granted', 'Pending', 'Withdrawn')`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "status" TYPE "public"."motions_status_enum_old" USING "status"::"text"::"public"."motions_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "status" SET DEFAULT 'Draft'`);
        await queryRunner.query(`DROP TYPE "public"."motions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."motions_status_enum_old" RENAME TO "motions_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."motions_type_enum_old" AS ENUM('Motion for Continuance', 'Motion for Default Judgment', 'Motion for Protective Order', 'Motion for Reconsideration', 'Motion for Sanctions', 'Motion for Summary Judgment', 'Motion in Limine', 'Motion to Amend', 'Motion to Compel', 'Motion to Dismiss', 'Motion to Strike', 'Other')`);
        await queryRunner.query(`ALTER TABLE "motions" ALTER COLUMN "type" TYPE "public"."motions_type_enum_old" USING "type"::"text"::"public"."motions_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."motions_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."motions_type_enum_old" RENAME TO "motions_type_enum"`);
        await queryRunner.query(`ALTER TABLE "case_phases" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "case_phases" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "password" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."time_entries_status_enum_old" AS ENUM('Approved', 'Billed', 'Draft', 'Submitted', 'Written Off')`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "status" TYPE "public"."time_entries_status_enum_old" USING "status"::"text"::"public"."time_entries_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "status" SET DEFAULT 'Draft'`);
        await queryRunner.query(`DROP TYPE "public"."time_entries_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."time_entries_status_enum_old" RENAME TO "time_entries_status_enum"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "total" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "duration" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "case_id" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_6ce0421e9bbc3b052184caf44c" ON "time_entries" ("billable", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_177f4415839baae541187a672d" ON "time_entries" ("status", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b33d2f7170600d7250ea875203" ON "time_entries" ("case_id", "date") `);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."cases_status_enum_old" AS ENUM('Active', 'Archived', 'Closed', 'Discovery', 'On Hold', 'Open', 'Settled', 'Trial')`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "status" TYPE "public"."cases_status_enum_old" USING "status"::"text"::"public"."cases_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "status" SET DEFAULT 'Open'`);
        await queryRunner.query(`DROP TYPE "public"."cases_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cases_status_enum_old" RENAME TO "cases_status_enum"`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "collectionDate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "evidenceType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "evidence_items" ALTER COLUMN "evidenceNumber" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "clientType" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "clients" ALTER COLUMN "clientNumber" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum_old" AS ENUM('Draft', 'Overdue', 'Paid', 'Partial', 'Sent', 'Viewed', 'Written Off')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum_old" USING "status"::"text"::"public"."invoices_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'Draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoices_status_enum_old" RENAME TO "invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "dueDate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoiceDate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "matterDescription" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "clientName" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "client_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "case_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "invoice_number" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_559333e87dd4e0f4df6dda4453" ON "invoices" ("dueDate", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8149db08955d2790ba626d74b6" ON "invoices" ("client_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_167a8092c79b7a2bc2cc18249e" ON "invoices" ("case_id", "status") `);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5534ba11e10f1a9953cbdaabf16" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
    }

}
