import { MigrationInterface, QueryRunner } from "typeorm";

export class AddMattersTable1766068192264 implements MigrationInterface {
    name = 'AddMattersTable1766068192264'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb49ffedefc177517b9ccfd650"`);
        await queryRunner.query(`CREATE TABLE "discovery_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "type" "public"."discovery_requests_type_enum" NOT NULL, "title" character varying(500) NOT NULL, "description" text, "status" "public"."discovery_requests_status_enum" NOT NULL DEFAULT 'DRAFT', "requestNumber" character varying(50), "dateSent" date, "dateReceived" date, "dueDate" date, "dateResponded" date, "requestingParty" character varying(200), "respondingParty" character varying(200), "numberOfRequests" integer NOT NULL DEFAULT '0', "numberOfResponses" integer NOT NULL DEFAULT '0', "numberOfObjections" integer NOT NULL DEFAULT '0', "requestItems" jsonb, "responses" jsonb, "objections" jsonb, "notes" text, "metadata" jsonb, "assignedTo" uuid, "createdBy" uuid NOT NULL, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_d932ebab08598c0372a95b9863b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "depositions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "deponentName" character varying(300) NOT NULL, "deponentTitle" character varying(100), "deponentOrganization" character varying(200), "type" "public"."depositions_type_enum" NOT NULL DEFAULT 'ORAL', "status" "public"."depositions_status_enum" NOT NULL DEFAULT 'SCHEDULED', "scheduledDate" TIMESTAMP, "actualStartTime" TIMESTAMP, "actualEndTime" TIMESTAMP, "durationMinutes" integer, "location" character varying(500), "courtReporter" character varying(300), "videographer" character varying(300), "attendees" jsonb, "summary" text, "keyTestimony" text, "exhibits" jsonb, "transcriptPath" character varying(500), "videoPath" character varying(500), "isTranscriptOrdered" boolean NOT NULL DEFAULT false, "transcriptOrderedDate" date, "transcriptReceivedDate" date, "estimatedCost" numeric(10,2), "actualCost" numeric(10,2), "notes" text, "metadata" jsonb, "assignedAttorney" uuid, "createdBy" uuid NOT NULL, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_3cc3f3d7bcbc9f19cbffe3a0b03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "esi_sources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "sourceName" character varying(300) NOT NULL, "sourceType" "public"."esi_sources_sourcetype_enum" NOT NULL, "status" "public"."esi_sources_status_enum" NOT NULL DEFAULT 'IDENTIFIED', "description" text, "location" character varying(500), "custodian" character varying(300), "custodianId" uuid, "dateIdentified" date, "datePreserved" date, "dateCollected" date, "dateProcessed" date, "estimatedVolume" bigint, "actualVolume" bigint, "volumeUnit" character varying(50), "dateRangeStart" date, "dateRangeEnd" date, "fileTypes" jsonb, "searchTerms" text, "isEncrypted" boolean NOT NULL DEFAULT false, "requiresSpecialProcessing" boolean NOT NULL DEFAULT false, "processingNotes" text, "collectionMethod" character varying(500), "collectionVendor" character varying(300), "collectionCost" numeric(10,2), "processingCost" numeric(10,2), "notes" text, "metadata" jsonb, "assignedTo" uuid, "createdBy" uuid NOT NULL, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_ea6261e334a7f085b8a5b445992" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "legal_holds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "holdName" character varying(300) NOT NULL, "holdNumber" character varying(100), "status" "public"."legal_holds_status_enum" NOT NULL DEFAULT 'DRAFT', "description" text NOT NULL, "holdInstructions" text NOT NULL, "issueDate" date NOT NULL, "effectiveDate" date, "releaseDate" date, "expirationDate" date, "custodians" jsonb NOT NULL, "totalCustodians" integer NOT NULL DEFAULT '0', "acknowledgedCount" integer NOT NULL DEFAULT '0', "pendingCount" integer NOT NULL DEFAULT '0', "dataSourcesToPreserve" jsonb, "notifications" jsonb, "reminderIntervalDays" integer NOT NULL DEFAULT '0', "lastReminderDate" date, "nextReminderDate" date, "isAutoReminder" boolean NOT NULL DEFAULT true, "releaseReason" text, "releaseNotes" text, "notes" text, "metadata" jsonb, "issuedBy" uuid, "releasedBy" uuid, "createdBy" uuid NOT NULL, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_bbe3e0c98678909493a90442dfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "privilege_log_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "privilegeLogNumber" character varying(100) NOT NULL, "batesNumber" character varying(100), "documentId" character varying(100), "documentDate" date NOT NULL, "author" character varying(300) NOT NULL, "recipients" jsonb, "ccRecipients" jsonb, "documentType" character varying(100), "description" text NOT NULL, "privilegeType" "public"."privilege_log_entries_privilegetype_enum" NOT NULL, "privilegeBasis" text, "status" "public"."privilege_log_entries_status_enum" NOT NULL DEFAULT 'CLAIMED', "isRedacted" boolean NOT NULL DEFAULT false, "redactionDetails" text, "pageCount" integer, "custodian" character varying(300), "custodianId" uuid, "filePath" character varying(500), "challengeNotes" text, "dateChallenged" date, "dateResolved" date, "notes" text, "metadata" jsonb, "reviewedBy" uuid, "createdBy" uuid NOT NULL, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_7ccb8cb3d34245ec8e88a11dcc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."custodians_status_enum" AS ENUM('IDENTIFIED', 'NOTIFIED', 'INTERVIEWED', 'DATA_COLLECTED', 'HOLD_RELEASED', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "custodians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "caseId" uuid NOT NULL, "firstName" character varying(200) NOT NULL, "lastName" character varying(200) NOT NULL, "fullName" character varying(400) NOT NULL, "email" character varying(300), "phone" character varying(50), "department" character varying(200), "title" character varying(200), "organization" character varying(300), "status" "public"."custodians_status_enum" NOT NULL DEFAULT 'IDENTIFIED', "dateIdentified" date, "dateNotified" date, "dateInterviewed" date, "dataCollectionDate" date, "isKeyPlayer" boolean NOT NULL DEFAULT false, "relevance" text, "dataSources" jsonb, "isOnLegalHold" boolean NOT NULL DEFAULT false, "legalHoldId" uuid, "legalHoldDate" date, "legalHoldReleasedDate" date, "interviews" jsonb, "notes" text, "metadata" jsonb, "assignedTo" uuid, "createdBy" uuid NOT NULL, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_3f24b16cec05a0df34f31dbafe1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "parties" DROP COLUMN "organization"`);
        await queryRunner.query(`ALTER TABLE "parties" DROP COLUMN "counsel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_167a8092c79b7a2bc2cc18249e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1d271efcbf097c3fec7196dc5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "case_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "case_id" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."parties_role_enum" RENAME TO "parties_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."parties_role_enum" AS ENUM('plaintiff', 'defendant', 'petitioner', 'respondent', 'appellant', 'appellee', 'third_party', 'intervenor', 'witness', 'expert')`);
        await queryRunner.query(`ALTER TABLE "parties" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "parties" ALTER COLUMN "role" TYPE "public"."parties_role_enum" USING "role"::"text"::"public"."parties_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."parties_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."parties_type_enum" RENAME TO "parties_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."parties_type_enum" AS ENUM('individual', 'corporation', 'government', 'organization', 'other')`);
        await queryRunner.query(`ALTER TABLE "parties" ALTER COLUMN "type" TYPE "public"."parties_type_enum" USING "type"::"text"::"public"."parties_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."parties_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "cases" DROP CONSTRAINT "FK_fbf8265e90624733f68ff5333ad"`);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "clientId" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b33d2f7170600d7250ea875203"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e104c17d0b5eaf02a099d6fdb"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP COLUMN "case_id"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD "case_id" uuid`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum" RENAME TO "users_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'partner', 'senior_associate', 'associate', 'junior_associate', 'paralegal', 'legal_assistant', 'clerk', 'intern', 'accountant', 'billing_specialist', 'it_admin', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum_old"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c162e1fe9d744b0721daea3b1c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying(200)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "permissions" jsonb`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "caseId" uuid`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "caseId" uuid`);
        await queryRunner.query(`ALTER TABLE "citations" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "citations" ADD "caseId" uuid`);
        await queryRunner.query(`ALTER TABLE "advisors" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "advisors" ADD "caseId" uuid`);
        await queryRunner.query(`ALTER TABLE "experts" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "experts" ADD "caseId" uuid`);
        await queryRunner.query(`ALTER TABLE "case_strategies" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "case_strategies" ADD "caseId" uuid NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b1d271efcbf097c3fec7196dc5" ON "invoices" ("case_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_167a8092c79b7a2bc2cc18249e" ON "invoices" ("case_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e104c17d0b5eaf02a099d6fdb" ON "time_entries" ("case_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b33d2f7170600d7250ea875203" ON "time_entries" ("case_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_c162e1fe9d744b0721daea3b1c" ON "users" ("department") `);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_b1d271efcbf097c3fec7196dc50" FOREIGN KEY ("case_id") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cases" ADD CONSTRAINT "FK_fbf8265e90624733f68ff5333ad" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_3e104c17d0b5eaf02a099d6fdb6" FOREIGN KEY ("case_id") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_84de0ffddf4e9d1724b15d0e245" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pleadings" ADD CONSTRAINT "FK_12db713e66ce836339aefed03c8" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discovery_requests" ADD CONSTRAINT "FK_85804f25efa249f7bd382ba081b" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "depositions" ADD CONSTRAINT "FK_6efae8012275e59f1260ccf6723" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "esi_sources" ADD CONSTRAINT "FK_cb7a0b183891c70029225776806" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "legal_holds" ADD CONSTRAINT "FK_d4f91906d78deb75fd5aaa20977" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "privilege_log_entries" ADD CONSTRAINT "FK_d49ad88090edd3a6f30179a8c87" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "FK_cdb2a3a09ad9cd0d6f431de9793" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_86730c0199f90946e3694b60f9f" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD CONSTRAINT "FK_b3d3e6ad7b18f26dd4564c057a4" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "citations" ADD CONSTRAINT "FK_2c109e0fc3ebd8a3b55202accde" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "advisors" ADD CONSTRAINT "FK_cd2a13f7cf4cba6b6ef9d9b5b20" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experts" ADD CONSTRAINT "FK_331af396ae468fec26274d910a2" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "case_strategies" ADD CONSTRAINT "FK_c61912d51d4f4a1c304ca012223" FOREIGN KEY ("caseId") REFERENCES "cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "case_strategies" DROP CONSTRAINT "FK_c61912d51d4f4a1c304ca012223"`);
        await queryRunner.query(`ALTER TABLE "experts" DROP CONSTRAINT "FK_331af396ae468fec26274d910a2"`);
        await queryRunner.query(`ALTER TABLE "advisors" DROP CONSTRAINT "FK_cd2a13f7cf4cba6b6ef9d9b5b20"`);
        await queryRunner.query(`ALTER TABLE "citations" DROP CONSTRAINT "FK_2c109e0fc3ebd8a3b55202accde"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP CONSTRAINT "FK_b3d3e6ad7b18f26dd4564c057a4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_86730c0199f90946e3694b60f9f"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "FK_cdb2a3a09ad9cd0d6f431de9793"`);
        await queryRunner.query(`ALTER TABLE "privilege_log_entries" DROP CONSTRAINT "FK_d49ad88090edd3a6f30179a8c87"`);
        await queryRunner.query(`ALTER TABLE "legal_holds" DROP CONSTRAINT "FK_d4f91906d78deb75fd5aaa20977"`);
        await queryRunner.query(`ALTER TABLE "esi_sources" DROP CONSTRAINT "FK_cb7a0b183891c70029225776806"`);
        await queryRunner.query(`ALTER TABLE "depositions" DROP CONSTRAINT "FK_6efae8012275e59f1260ccf6723"`);
        await queryRunner.query(`ALTER TABLE "discovery_requests" DROP CONSTRAINT "FK_85804f25efa249f7bd382ba081b"`);
        await queryRunner.query(`ALTER TABLE "pleadings" DROP CONSTRAINT "FK_12db713e66ce836339aefed03c8"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_84de0ffddf4e9d1724b15d0e245"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_3e104c17d0b5eaf02a099d6fdb6"`);
        await queryRunner.query(`ALTER TABLE "cases" DROP CONSTRAINT "FK_fbf8265e90624733f68ff5333ad"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_b1d271efcbf097c3fec7196dc50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c162e1fe9d744b0721daea3b1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b33d2f7170600d7250ea875203"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e104c17d0b5eaf02a099d6fdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_167a8092c79b7a2bc2cc18249e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1d271efcbf097c3fec7196dc5"`);
        await queryRunner.query(`ALTER TABLE "case_strategies" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "case_strategies" ADD "caseId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "experts" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "experts" ADD "caseId" character varying`);
        await queryRunner.query(`ALTER TABLE "advisors" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "advisors" ADD "caseId" character varying`);
        await queryRunner.query(`ALTER TABLE "citations" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "citations" ADD "caseId" character varying`);
        await queryRunner.query(`ALTER TABLE "calendar_events" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" ADD "caseId" character varying`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "caseId"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "caseId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "permissions" text array NOT NULL DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department" character varying(100)`);
        await queryRunner.query(`CREATE INDEX "IDX_c162e1fe9d744b0721daea3b1c" ON "users" ("department") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum_old" AS ENUM('accountant', 'admin', 'associate', 'attorney', 'billing_specialist', 'clerk', 'client', 'intern', 'it_admin', 'junior_associate', 'legal_assistant', 'paralegal', 'partner', 'senior_associate', 'staff', 'super_admin', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum_old" USING "role"::"text"::"public"."users_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'staff'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."users_role_enum_old" RENAME TO "users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP COLUMN "case_id"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD "case_id" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_3e104c17d0b5eaf02a099d6fdb" ON "time_entries" ("case_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b33d2f7170600d7250ea875203" ON "time_entries" ("case_id", "date") `);
        await queryRunner.query(`ALTER TABLE "cases" ALTER COLUMN "clientId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cases" ADD CONSTRAINT "FK_fbf8265e90624733f68ff5333ad" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TYPE "public"."parties_type_enum_old" AS ENUM('Appellant', 'Appellee', 'Defendant', 'Expert Witness', 'Other', 'Petitioner', 'Plaintiff', 'Respondent', 'Third Party', 'Witness', 'corporation', 'government', 'individual', 'organization', 'other')`);
        await queryRunner.query(`ALTER TABLE "parties" ALTER COLUMN "type" TYPE "public"."parties_type_enum_old" USING "type"::"text"::"public"."parties_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."parties_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."parties_type_enum_old" RENAME TO "parties_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."parties_role_enum_old" AS ENUM('Co-Party', 'Guardian', 'Interested Party', 'Primary', 'Representative', 'appellant', 'appellee', 'defendant', 'expert', 'intervenor', 'petitioner', 'plaintiff', 'respondent', 'third_party', 'witness')`);
        await queryRunner.query(`ALTER TABLE "parties" ALTER COLUMN "role" TYPE "public"."parties_role_enum_old" USING "role"::"text"::"public"."parties_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "parties" ALTER COLUMN "role" SET DEFAULT 'Primary'`);
        await queryRunner.query(`DROP TYPE "public"."parties_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."parties_role_enum_old" RENAME TO "parties_role_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "case_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "case_id" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_b1d271efcbf097c3fec7196dc5" ON "invoices" ("case_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_167a8092c79b7a2bc2cc18249e" ON "invoices" ("case_id", "status") `);
        await queryRunner.query(`ALTER TABLE "parties" ADD "counsel" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "parties" ADD "organization" character varying(255)`);
        await queryRunner.query(`DROP TABLE "custodians"`);
        await queryRunner.query(`DROP TYPE "public"."custodians_status_enum"`);
        await queryRunner.query(`DROP TABLE "privilege_log_entries"`);
        await queryRunner.query(`DROP TABLE "legal_holds"`);
        await queryRunner.query(`DROP TABLE "esi_sources"`);
        await queryRunner.query(`DROP TABLE "depositions"`);
        await queryRunner.query(`DROP TABLE "discovery_requests"`);
        await queryRunner.query(`CREATE INDEX "IDX_cb49ffedefc177517b9ccfd650" ON "users" ("isActive", "role") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
